/**
 * Track P Session P7 — Negotiation rehearsal type contracts.
 *
 * The founder writes a counter; Olivia plays the investor pushing
 * back. Multi-turn — each turn, the caller passes the prior history
 * and the founder's latest message. Stateless on the server side
 * (the founder's UI owns the conversation thread).
 */
import { z } from 'zod';

import { SMART_BANDS_ORDERED, type SmartBand } from './types';

/** A single message in the rehearsal thread. */
export interface RehearsalTurn {
  readonly role: 'founder' | 'investor';
  readonly content: string;
}

export const RehearsalTurnSchema = z.object({
  role: z.enum(['founder', 'investor']),
  content: z.string().min(1).max(4000),
});

export interface RehearsalRequest {
  /** The deal analysis context — provides band + critical issues for the investor's voice. */
  readonly dealAnalysisId: string;
  /** Prior turns in the rehearsal. Empty on the first turn. */
  readonly history: ReadonlyArray<RehearsalTurn>;
  /** The founder's latest counter / argument. Required. */
  readonly founderTurn: string;
  /** Optional founder name (improves voice) and investor name (Olivia plays this role). */
  readonly founderName?: string;
  readonly investorName?: string;
}

export const RehearsalPostBodySchema = z.object({
  dealAnalysisId: z.string().min(1),
  history: z.array(RehearsalTurnSchema).max(40).optional(),
  founderTurn: z.string().min(1).max(4000),
  founderName: z.string().min(1).max(120).optional(),
  investorName: z.string().min(1).max(120).optional(),
});

/** The investor response generated by the cascade. */
export interface RehearsalResponse {
  readonly investorMessage: string;
  /** Stance signal the cascade flagged in this turn — 'pushback' / 'concede' / 'walk' / 'neutral'. */
  readonly stance: 'pushback' | 'concede' | 'walk' | 'neutral';
  readonly providerId: string;
  readonly modelId: string;
  readonly runtimeMode: 'live' | 'mock';
  readonly attempts: ReadonlyArray<{
    readonly providerId: string;
    readonly modelId: string;
    readonly success: boolean;
    readonly durationMs: number;
  }>;
}

export const REHEARSAL_LIMITS = Object.freeze({
  MIN_BODY: 40,
  MAX_BODY: 1500,
});

const StanceSchema = z.enum(['pushback', 'concede', 'walk', 'neutral']);

export const CascadeRehearsalSchema = z.object({
  investorMessage: z
    .string()
    .min(REHEARSAL_LIMITS.MIN_BODY)
    .max(REHEARSAL_LIMITS.MAX_BODY),
  stance: StanceSchema,
});

/** Per-band stance hint used by the deterministic fallback. */
export const REHEARSAL_STANCE_BY_BAND: Readonly<
  Record<SmartBand, 'pushback' | 'walk' | 'neutral' | 'concede'>
> = Object.freeze({
  red: 'pushback',
  orange: 'pushback',
  yellow: 'pushback',
  blue: 'neutral',
  green: 'concede',
});

/* Touch the imported list so a future tree-shake pass keeps it. */
void SMART_BANDS_ORDERED;
