/**
 * 75 deck archetypes — Studio Olivia Library.
 *
 * Source: `D:\Studio-Olivia\StudioOliviaGrandMaster (2).jsx` lines 17 + 19.
 * Lifted byte-for-byte (text content preserved verbatim) and typed strictly
 * against `DeckArchetype` so misspellings of `cat` / missing `stage` /
 * stray fields surface at typecheck rather than runtime.
 *
 * # Two halves
 *
 * - **1–53:** the original prototype-curated archetype set, span the full
 *   category map (classic, saas, ai_modern, london_uk, fintech, consumer,
 *   industry_template, vc_framework, ai_template).
 * - **54–75:** "Real Verified Decks" — historical raises with concrete
 *   amounts + years + slide counts (the source comment in the prototype
 *   reads `// REAL VERIFIED DECKS (54-75)`).
 *
 * Per `feedback_world_class_standard` the math + content of the prototype
 * is preserved; the rebuild only replaces the inline-style render layer.
 */

import type { DeckArchetype } from "./types";

export const DECK_ARCHETYPES: readonly DeckArchetype[] = [
  // ── 1–53: Original prototype archetypes ───────────────────────────
  { id: 1, name: "Airbnb", tag: "Minimalist Masterclass", cat: "classic", stage: ["Seed"], consensus: 4, insight: "Clarity beat polish. Ten words per slide.", fit: "London B2C founders who need to strip their deck to its essential claim.", olivia_action: "Strip fluff, enforce clarity — removes any slide that cannot survive a ten-word summary." },
  { id: 2, name: "Uber", tag: "Market Disruption", cat: "classic", stage: ["Seed", "Pre-seed"], consensus: 4, insight: "Sold the future, not the feature.", fit: "London founders disrupting a legacy industry — logistics, mobility, professional services, property.", olivia_action: "Vision-first mode — builds a before/after world framing before introducing the product." },
  { id: 3, name: "Buffer", tag: "Traction-First", cat: "saas", stage: ["Seed"], consensus: 4, insight: "Led with traction. MRR earns the right to be heard.", fit: "London SaaS founders with early MRR who lead with numbers rather than vision.", olivia_action: "Insert live metrics engine — pulls MRR, churn, and growth onto slide 3." },
  { id: 4, name: "LinkedIn", tag: "Network Model", cat: "saas", stage: ["Series B"], consensus: 3, insight: "No revenue — but a credible revenue roadmap.", fit: "London marketplace or network-effects founders at pre-revenue stage.", olivia_action: "Highlight compounding value — builds a network-effects flywheel diagram." },
  { id: 5, name: "Dropbox", tag: "Freemium SaaS", cat: "saas", stage: ["Seed", "Series A"], consensus: 2, insight: "Zero jargon. Understood in 30 seconds.", fit: "London productivity or developer tool founders who can demo in 30 seconds.", olivia_action: "Add demo video placeholder as slide 3." },
  { id: 6, name: "Tinder", tag: "Story-Driven UX", cat: "consumer", stage: ["Seed"], consensus: 1, insight: "Narrative empathy before product.", fit: "London consumer-facing app founders — lead with user empathy.", olivia_action: "Story-first narrative — opens with a user persona in distress." },
  { id: 7, name: "Slack", tag: "Anti-Email", cat: "saas", stage: ["Series A"], consensus: 1, insight: "Sell the transformation, not the tool.", fit: "London B2B founders replacing entrenched workflows.", olivia_action: "Transformation narrative — before/after working-world contrast." },
  { id: 8, name: "Front", tag: "Metrics Transparency", cat: "saas", stage: ["Seed", "Series A"], consensus: 1, insight: "Product on screen by slide 3.", fit: "London B2B founders with live product and clean UI.", olivia_action: "Product screenshot with annotated callouts as slide 3." },
  { id: 9, name: "Coinbase", tag: "Complex → Simple", cat: "fintech", stage: ["Seed"], consensus: 1, insight: "Education-first for emerging categories.", fit: "London deep tech or AI infrastructure founders pitching generalist VCs.", olivia_action: "Education-first slides 1-3 before problem/solution." },
  { id: 10, name: "Facebook", tag: "Hypergrowth", cat: "consumer", stage: ["Series A"], consensus: 1, insight: "Let the numbers speak.", fit: "London founders with hypergrowth metrics — lead with chart, not story.", olivia_action: "Metric-first — growth chart on slide 2." },
  { id: 11, name: "Synthesia", tag: "Gen AI Standard", cat: "ai_modern", stage: ["Series A"], consensus: 1, insight: "Quantify cost collapse.", fit: "London AI founders who can quantify specific cost-collapse from automation.", olivia_action: "Cost-collapse visuals — before/after cost comparison chart." },
  { id: 12, name: "Writer", tag: "Enterprise AI", cat: "ai_modern", stage: ["Series A"], consensus: 1, insight: "Lead with safety and compliance.", fit: "London enterprise AI founders in regulated sectors.", olivia_action: "Moat + compliance — AI governance and risk-mitigation slide." },
  { id: 13, name: "Gong", tag: "AI Revenue Play", cat: "ai_modern", stage: ["Series B"], consensus: 1, insight: "Tie AI directly to revenue uplift.", fit: "London AI founders who can attribute output to measurable revenue uplift.", olivia_action: "Revenue linkage — customer ROI calculator slide." },
  { id: 14, name: "Square", tag: "Ecosystem Flywheel", cat: "fintech", stage: ["Buyout"], consensus: 1, insight: "Single product to ecosystem.", fit: "London founders pitching multi-product ecosystem or strategic acquisition.", olivia_action: "Flywheel diagram showing how each product feeds the next." },
  { id: 15, name: "Mixpanel", tag: "Contrast-Giant", cat: "saas", stage: ["Series A"], consensus: 2, insight: "Sharp contrast against a known giant.", fit: "London analytics founders who can draw sharp contrast against dominant incumbent.", olivia_action: "Side-by-side comparison table with specific differentiators." },
  { id: 16, name: "Intercom", tag: "Minimalist 8-Slide", cat: "saas", stage: ["Series C"], consensus: 1, insight: "Eight slides. Zero fluff.", fit: "London Series B/C founders who trust metrics over narrative.", olivia_action: "Enforce 8-12 slide rule — flags duplicates." },
  { id: 17, name: "Copy.ai", tag: "AI SaaS Story", cat: "ai_modern", stage: ["Series A"], consensus: 2, insight: "Narrow the AI use-case tightly.", fit: "London AI founders with a tightly defined vertical use case.", olivia_action: "Niche-down — challenges any slide that broadens beyond stated vertical." },
  { id: 18, name: "Verbit", tag: "AI-Human Hybrid", cat: "ai_modern", stage: ["Seed"], consensus: 1, insight: "Make the AI-human loop legible.", fit: "London AI founders where human-in-the-loop is a feature, not limitation.", olivia_action: "Hybrid loop visual — process diagram showing AI vs human review." },
  { id: 19, name: "TransferWise", tag: "UK Challenger", cat: "london_uk", stage: ["Seed"], consensus: 1, insight: "Transparent fee comparison.", fit: "London fintech founders with transparent before/after fee comparison.", olivia_action: "Fee comparison table with incumbent vs. challenger costs." },
  { id: 20, name: "Monzo", tag: "UK Challenger Bank", cat: "london_uk", stage: ["Seed"], consensus: 1, insight: "Cult-brand aesthetic.", fit: "London consumer fintech founders whose brand identity is as strong as their metrics.", olivia_action: "Month-on-month growth charts with brand-consistent colour treatment." },
  { id: 21, name: "Seek AI", tag: "Niche-Down Gen AI", cat: "ai_modern", stage: ["Seed"], consensus: 1, insight: "Niche to one high-value use case.", fit: "London AI founders pitching a single, laser-focused use case.", olivia_action: "Single use-case focus — name the one job-to-be-done first." },
  { id: 22, name: "RapidCanvas", tag: "AI Simplification", cat: "ai_modern", stage: ["Seed"], consensus: 1, insight: "Position against build-it-yourself.", fit: "London AI founders positioning against the internal engineering team alternative.", olivia_action: "Build vs. buy comparison with TCO analysis." },
  { id: 23, name: "Sutro", tag: "Non-Technical", cat: "ai_modern", stage: ["Seed"], consensus: 1, insight: "Empower the non-technical creator.", fit: "London founders building for non-technical users — operators, marketers, compliance.", olivia_action: "Market expansion argument — non-technical access as market expansion." },
  { id: 24, name: "Artisan", tag: "Big Idea + Team", cat: "ai_modern", stage: ["Pre-seed"], consensus: 1, insight: "No traction? Vision + credible team.", fit: "London pre-seed founders trading on vision plus team strength alone.", olivia_action: "Two slides to team credibility before any product content." },
  { id: 25, name: "Anthropic/OpenAI", tag: "AI Defensibility", cat: "ai_modern", stage: ["Pre-seed", "Seed"], consensus: 1, insight: "Proprietary data, architecture, partnerships.", fit: "London AI founders with genuine moat — proprietary data, novel architecture.", olivia_action: "Dedicated moat slide enumerating each defensibility layer." },
  { id: 26, name: "Gradient Labs", tag: "London AI Specificity", cat: "london_uk", stage: ["Series A"], consensus: 1, insight: "£13M in one week with specificity.", fit: "London AI founders in regulated verticals with hyper-specific named customer ARR.", olivia_action: "Flags any ARR figure without a named customer reference." },
  { id: 27, name: "Viable", tag: "London Fintech Niche", cat: "london_uk", stage: ["Seed"], consensus: 1, insight: "14 slides max. Clear customer + pricing.", fit: "London seed founders wanting direct 14-slide structure with clear customer and pricing.", olivia_action: "Customer definition on slide 2, pricing on slide 8." },
  { id: 28, name: "Cleo", tag: "UK Fintech Unicorn", cat: "london_uk", stage: ["Series A"], consensus: 1, insight: "50% traction charts. Show don't tell.", fit: "London consumer fintech with strong growth curves — charts over claims.", olivia_action: "Month-on-month user and revenue growth charts first." },
  { id: 29, name: "Snuze", tag: "London Hardware", cat: "london_uk", stage: ["Seed"], consensus: 1, insight: "Hardware needs deployment schedule.", fit: "London hardware, IoT, or wearables founders.", olivia_action: "Hardware deployment timeline and unit economics breakout." },
  { id: 30, name: "YC Campaign", tag: "80-Investor Campaign", cat: "vc_framework", stage: ["Seed"], consensus: 1, insight: "The deck is 20% of the raise.", fit: "London founders running structured investor outreach campaigns.", olivia_action: "Investor targeting list alongside the deck." },
  { id: 31, name: "Disruptive AI", tag: "14-Slide AI/ML", cat: "industry_template", stage: ["Seed"], consensus: 1, insight: "Lead with precise SME pain stat.", fit: "London AI/ML founders opening with precise, verifiable pain statistic.", olivia_action: "Source the opening pain statistic via web search." },
  { id: 32, name: "SaaS Scalability", tag: "14-Slide B2B/B2C", cat: "industry_template", stage: ["Seed"], consensus: 1, insight: "Category analogy: X for Y.", fit: "London SaaS founders with strong category analogy.", olivia_action: "Stress-test the category analogy against London comparables." },
  { id: 33, name: "Fintech Revolution", tag: "Open Banking", cat: "industry_template", stage: ["Seed", "Series A"], consensus: 1, insight: "Regulatory credentials by slide 4.", fit: "London fintech founders establishing FCA authorisation by slide 4.", olivia_action: "Dedicated FCA/regulatory credentials slide." },
  { id: 34, name: "Healthtech", tag: "AI Diagnostics", cat: "industry_template", stage: ["Seed", "Series A"], consensus: 1, insight: "Clinical validation beats traction.", fit: "London healthtech founders where clinical validation is the primary signal.", olivia_action: "Clinical validation pathway slide." },
  { id: 35, name: "Climate Tech", tag: "Cleantech / Carbon", cat: "industry_template", stage: ["Seed"], consensus: 1, insight: "Policy tailwinds mandatory.", fit: "London cleantech founders showing UK/EU regulatory policy tailwinds.", olivia_action: "UK/EU policy timeline slide." },
  { id: 36, name: "Edtech", tag: "AI Tutors / Upskilling", cat: "industry_template", stage: ["Seed"], consensus: 1, insight: "Completion rate beats user count.", fit: "London edtech founders where learning outcomes beat raw user count.", olivia_action: "Learning funnel chart." },
  { id: 37, name: "Proptech", tag: "AI Valuations", cat: "industry_template", stage: ["Seed"], consensus: 1, insight: "Direct match for property analysis.", fit: "London proptech founders building AI-powered valuation for the UK market.", olivia_action: "Data source map showing UK property data feeds." },
  { id: 38, name: "Sequoia Capital", tag: "Universal 10-Slide", cat: "vc_framework", stage: ["Any"], consensus: 1, insight: "If in doubt, use Sequoia skeleton.", fit: "Default skeleton for any CLUES London founder.", olivia_action: "Always builds the Sequoia 10-slide spine first." },
  { id: 39, name: "YC Demo Day", tag: "2.5-Min Pitch", cat: "vc_framework", stage: ["Seed"], consensus: 1, insight: "Every slide is a 15-second claim.", fit: "London founders preparing for accelerator demo days.", olivia_action: "15-second claim test per slide." },
  { id: 40, name: "500 Startups", tag: "Seed Metrics", cat: "vc_framework", stage: ["Seed"], consensus: 1, insight: "Explicit metric benchmarks.", fit: "London seed founders needing CAC, LTV, MoM growth on slide face.", olivia_action: "Maps metrics to 500 Startups benchmarks." },
  { id: 41, name: "AI Series A", tag: "AI-Specific 2025", cat: "ai_template", stage: ["Series A"], consensus: 1, insight: "Tech stack slide matters again.", fit: "London AI founders at Series A needing detailed tech stack slide.", olivia_action: "Layered tech architecture diagram." },
  { id: 42, name: "Beautiful.ai", tag: "AI-Focused Template", cat: "ai_template", stage: ["Any"], consensus: 1, insight: "Tech roadmap slides earn space.", fit: "London tech founders needing product roadmap slide.", olivia_action: "Phased product and technology roadmap." },
  { id: 43, name: "Template.net AI", tag: "Multi-format", cat: "ai_template", stage: ["Any"], consensus: 1, insight: "Export flexibility matters.", fit: "London founders needing PDF, PPTX, and web embed formats.", olivia_action: "Format-agnostic master deck." },
  { id: 44, name: "Headline Series A", tag: "2026 Framework", cat: "ai_template", stage: ["Series A"], consensus: 1, insight: "Value Prop + Edge = live or die.", fit: "London Series A founders needing provable value prop and defensible edge.", olivia_action: "Requires founder to name competitive edge in one sentence." },
  { id: 45, name: "Slidestack AI", tag: "Modern Dark", cat: "ai_template", stage: ["Any"], consensus: 1, insight: "Dark backgrounds = tech-forward.", fit: "London AI or deep-tech founders with technical-forward brand.", olivia_action: "Dark-theme variant output." },
  { id: 46, name: "BeyondLabs AI", tag: "Meta-Tool: AI Pitch", cat: "ai_template", stage: ["Any"], consensus: 1, insight: "Pitch-deck-generation IS multi-LLM.", fit: "Validation for Olivia Studio itself as a product category.", olivia_action: "Multi-LLM validation — secondary model gap analysis." },
  { id: 47, name: "HubSpot 12", tag: "Real-World Archive", cat: "ai_template", stage: ["Any"], consensus: 1, insight: "Match the archetype first.", fit: "Archetype-routing reference — match stage, vertical, ask to closest archetype.", olivia_action: "Archetype routing — classification before generation." },
  { id: 48, name: "PitchDeckHunt", tag: "Curated Archive", cat: "ai_template", stage: ["Any"], consensus: 1, insight: "Steal composition, not content.", fit: "Layout library reference — slide composition and information hierarchy.", olivia_action: "Layout library for slide composition templates." },
  { id: 49, name: "Guy Kawasaki", tag: "10/20/30", cat: "vc_framework", stage: ["Pre-seed", "Seed"], consensus: 0, insight: "Canonical constraint framework.", fit: "Pre-seed London founders needing hard constraints to stop over-engineering.", olivia_action: "Enforce 10/20/30 rule." },
  { id: 50, name: "Canva", tag: "Massive Market Narrow Entry", cat: "classic", stage: ["Seed", "Series A"], consensus: 0, insight: "Massive-market + narrow-entry logic.", fit: "London founders entering massive market through narrow, well-defined wedge.", olivia_action: "Market expansion slide: wedge → adjacency → total market." },
  { id: 51, name: "Revolut", tag: "Pre-Product Waitlist", cat: "london_uk", stage: ["Pre-seed", "Seed"], consensus: 0, insight: "Pre-product traction proves demand.", fit: "London pre-product founders with waitlist demand proof.", olivia_action: "Waitlist dashboard slide." },
  { id: 52, name: "YouTube", tag: "Content Flywheel", cat: "consumer", stage: ["Series A"], consensus: 0, insight: "Let the flywheel curves speak.", fit: "London platform founders with two-sided flywheel compounding.", olivia_action: "Two-sided flywheel diagram." },
  { id: 53, name: "Snapchat", tag: "Contrarian Thesis", cat: "consumer", stage: ["Series A"], consensus: 0, insight: "Contrarian bet against permanence.", fit: "London founders challenging widely-held market assumptions.", olivia_action: "'Conventional wisdom is wrong' slide." },

  // ── 54–75: Real Verified Decks (historical raises) ────────────────
  { id: 54, name: "Airbnb (2008)", tag: "10-Slide Classic", cat: "classic", stage: ["Pre-seed"], consensus: 5, insight: "Simple problem + massive TAM. Raised $600K.", fit: "London founders proving radical simplicity beats polish.", olivia_action: "Strip to 10 slides max.", raised: "$600K", year: 2008, slideCount: 10 },
  { id: 55, name: "Uber (2008)", tag: "Disruption + Market", cat: "classic", stage: ["Pre-seed"], consensus: 5, insight: "Predicted smartphone future. Raised $200K.", fit: "London founders betting on emerging platform shifts.", olivia_action: "Market size + binary decision slide.", raised: "$200K", year: 2008, slideCount: 22 },
  { id: 56, name: "Buffer (2011)", tag: "Traction Transparency", cat: "saas", stage: ["Seed"], consensus: 5, insight: "Real MRR on slide 3. Raised ~$500K.", fit: "London SaaS with real metrics — transparency wins trust.", olivia_action: "MRR, churn, MoM growth on slide 3.", raised: "$500K", year: 2011, slideCount: 12 },
  { id: 57, name: "Dropbox (2010)", tag: "Video Demo", cat: "saas", stage: ["Seed"], consensus: 4, insight: "Demo + 4 bullets. Raised $1.2M.", fit: "London B2C with demo-friendly product.", olivia_action: "Demo video embed + 4-bullet problem/solution.", raised: "$1.2M", year: 2010, slideCount: 10 },
  { id: 58, name: "Revolut (2015)", tag: "UK Challenger Fintech", cat: "london_uk", stage: ["Seed"], consensus: 4, insight: "Fee comparison + waitlist. Raised £1.5M.", fit: "London fintech — transparent fee comparison + waitlist.", olivia_action: "FCA/EMI pathway timeline.", raised: "£1.5M", year: 2015, slideCount: 14 },
  { id: 59, name: "Monzo (2015)", tag: "Cult-Brand", cat: "london_uk", stage: ["Seed"], consensus: 4, insight: "50% traction charts + cult aesthetic.", fit: "London consumer fintech building brand and community.", olivia_action: "Month-on-month growth charts with brand treatment.", raised: "£1M+", year: 2015, slideCount: 15 },
  { id: 60, name: "Wise", tag: "Fee Transparency", cat: "london_uk", stage: ["Seed"], consensus: 4, insight: "UK-born challenger, transparent pricing.", fit: "London cross-border / payments founders.", olivia_action: "Fee comparison table from public pricing pages.", raised: "£1M+", year: 2011, slideCount: 12 },
  { id: 61, name: "Intercom (2012)", tag: "Minimalist 8-Slide", cat: "saas", stage: ["Seed"], consensus: 4, insight: "8 slides. Raised $600K.", fit: "London SaaS needing brutal concision.", olivia_action: "Enforce 8-12 slides, merge duplicates.", raised: "$600K", year: 2012, slideCount: 8 },
  { id: 62, name: "Figma (2013)", tag: "Pre-Product Vision", cat: "ai_modern", stage: ["Pre-seed"], consensus: 4, insight: "Community + education. Raised $3.8M.", fit: "London dev-tools founders with community-led growth.", olivia_action: "Team + vision trade-off.", raised: "$3.8M", year: 2013, slideCount: 12 },
  { id: 63, name: "Mattermark", tag: "Real ARR", cat: "saas", stage: ["Series A"], consensus: 3, insight: "$1.5M ARR + customer diversification.", fit: "London B2B SaaS at Series A with real revenue.", olivia_action: "Cohort retention chart + ARR waterfall.", raised: "$1.5M", year: 2015, slideCount: 18 },
  { id: 64, name: "Perplexity AI", tag: "AI Search Moat", cat: "ai_modern", stage: ["Seed"], consensus: 4, insight: "Proprietary data + architecture defensibility.", fit: "London AI founders with data or architecture moat.", olivia_action: "Defensibility slide — proprietary data + partnerships.", raised: "$250M+", year: 2024, slideCount: 14 },
  { id: 65, name: "Sequoia 10-Slide", tag: "Universal Template", cat: "vc_framework", stage: ["Any"], consensus: 5, insight: "Purpose → problem → solution → why now → market → model → team → financials → ask.", fit: "Default skeleton for any London founder.", olivia_action: "Apply Sequoia structure first, overlay archetype.", slideCount: 10 },
  { id: 66, name: "YC Demo Day", tag: "2.5-Min 10-Slide", cat: "vc_framework", stage: ["Seed"], consensus: 5, insight: "Every slide = 15-second claim.", fit: "London accelerator demo day prep.", olivia_action: "15-second claim test per slide.", slideCount: 10 },
  { id: 67, name: "Guy Kawasaki", tag: "Canonical Constraint", cat: "vc_framework", stage: ["Pre-seed", "Seed"], consensus: 4, insight: "10 slides, 20 min, 30pt font.", fit: "London founders needing strict format discipline.", olivia_action: "Enforce 10/20/30 rule.", slideCount: 10 },
  { id: 68, name: "Coinbase (2012)", tag: "Education-First", cat: "fintech", stage: ["Seed"], consensus: 4, insight: "Complex tech made simple.", fit: "London crypto/web3 founders explaining new categories.", olivia_action: "Category explainer slides 1-3.", year: 2012, slideCount: 15 },
  { id: 69, name: "WeWork (2012)", tag: "Ecosystem Flywheel", cat: "industry_template", stage: ["Series A"], consensus: 3, insight: "Single product → ecosystem.", fit: "London workspace or sector-specific platform founders.", olivia_action: "Ecosystem flywheel diagram.", year: 2012, slideCount: 16 },
  { id: 70, name: "Synthesia (2021)", tag: "Gen AI Standard", cat: "ai_modern", stage: ["Series A"], consensus: 4, insight: "Cost collapse quantified.", fit: "London AI founders quantifying the cost-collapse curve.", olivia_action: "Before/after cost comparison with customer reference.", raised: "£90M+", year: 2021, slideCount: 14 },
  { id: 71, name: "Gradient Labs", tag: "London AI Specificity", cat: "london_uk", stage: ["Series A"], consensus: 4, insight: "£13M in one week with hyper-specific ARR.", fit: "London AI targeting a single regulated vertical.", olivia_action: "Named customer ARR narrative.", raised: "£13M", year: 2024, slideCount: 13 },
  { id: 72, name: "Cleo", tag: "UK Fintech Unicorn", cat: "london_uk", stage: ["Series A"], consensus: 4, insight: "50% traction charts. Show, don't tell.", fit: "London fintech — charts over words.", olivia_action: "Traction-chart dominant.", year: 2018, slideCount: 14 },
  { id: 73, name: "Mixpanel", tag: "Contrast-Giant", cat: "saas", stage: ["Series A"], consensus: 4, insight: "Sharp contrast vs giant + metrics.", fit: "London analytics founders challenging incumbents.", olivia_action: "Named competitor comparison table.", raised: "$65M", year: 2014, slideCount: 18 },
  { id: 74, name: "Mint", tag: "Superior UX", cat: "fintech", stage: ["Seed"], consensus: 3, insight: "Easy UI + competitor contrast. Raised $4.7M.", fit: "London fintech with UX advantage over legacy tools.", olivia_action: "Side-by-side UX comparison.", raised: "$4.7M", year: 2007, slideCount: 12 },
  { id: 75, name: "Snapchat", tag: "Contrarian Thesis", cat: "consumer", stage: ["Series A"], consensus: 3, insight: "Bet against permanence.", fit: "London founders with counter-consensus thesis.", olivia_action: "Contrarian framing slide.", year: 2012, slideCount: 14 },
];
