/**
 * OLIVIA BRAIN — Agent Registry
 *
 * Static definitions for all 250 autonomous agents.
 * This is the code-level source of truth for agent metadata
 * used to seed the database and render the dashboard.
 *
 * Agent ID Format: O{category}-{number}
 * - O1-xxx: Persona Agents (Olivia, Cristiano, Emelia capabilities)
 * - O2-xxx: Domain Intelligence (CLUES, LifeScore, Real Estate, etc.)
 * - O3-xxx: Infrastructure Agents (Memory, Orchestration, Compliance)
 * - O4-xxx: Integration Agents (External APIs, Product Hookups)
 */

import type { AgentDefinition, AgentGroupDefinition } from "./types";

// ─────────────────────────────────────────────
// Agent Groups
// ─────────────────────────────────────────────

export const AGENT_GROUPS: AgentGroupDefinition[] = [
  // PERSONA AGENTS (1x)
  { code: "1A", name: "Olivia™ Client Interaction", description: "Bilateral client communication, video responses, intake flows", sortOrder: 1, category: "persona" },
  { code: "1B", name: "Cristiano™ Judge System", description: "Unilateral verdict rendering, final decisions, authoritative outputs", sortOrder: 2, category: "persona" },
  { code: "1C", name: "Emelia™ Support Operations", description: "Back-end support, technical assistance, knowledge base management", sortOrder: 3, category: "persona" },
  { code: "1D", name: "Persona Orchestration", description: "Cross-persona coordination, handoffs, escalation routing", sortOrder: 4, category: "persona" },

  // DOMAIN INTELLIGENCE (2x)
  { code: "2A", name: "CLUES Questionnaire Engine", description: "Paragraphical extraction, adaptive questioning, module selection", sortOrder: 5, category: "domain" },
  { code: "2B", name: "SMART Score™ Calculation", description: "City scoring, comparison generation, match algorithms", sortOrder: 6, category: "domain" },
  { code: "2C", name: "LifeScore Integration", description: "20 LifeScore module apps, wellness metrics, life optimization", sortOrder: 7, category: "domain" },
  { code: "2D", name: "Real Estate Intelligence", description: "Property analysis, market data, valuation, neighborhood scoring", sortOrder: 8, category: "domain" },
  { code: "2E", name: "Relocation Intelligence", description: "Cost of living, transit, safety, schools, environmental data", sortOrder: 9, category: "domain" },
  { code: "2F", name: "Financial Analysis", description: "Mortgage calculations, investment analysis, affordability scoring", sortOrder: 10, category: "domain" },
  { code: "2G", name: "Immigration & Visa", description: "Visa requirements, pathway analysis, documentation assistance", sortOrder: 11, category: "domain" },
  { code: "2H", name: "Pitch Intelligence", description: "Pitch deck archetypes, business plan templates, investor personas, slide optimization", sortOrder: 12, category: "domain" },

  // INFRASTRUCTURE (3x)
  { code: "3A", name: "Memory Systems", description: "Episodic, semantic, procedural memory management", sortOrder: 12, category: "infrastructure" },
  { code: "3B", name: "9-Model Cascade", description: "LLM orchestration, model routing, cascade execution", sortOrder: 13, category: "infrastructure" },
  { code: "3C", name: "RAG Pipeline", description: "Document ingestion, embedding, retrieval, citation", sortOrder: 14, category: "infrastructure" },
  { code: "3D", name: "Voice & Avatar", description: "TTS, STT, avatar generation, realtime transport", sortOrder: 15, category: "infrastructure" },
  { code: "3E", name: "Compliance & Safety", description: "PII redaction, fair housing, guardrails, audit logging", sortOrder: 16, category: "infrastructure" },
  { code: "3F", name: "Observability", description: "Tracing, metrics, alerting, performance monitoring", sortOrder: 17, category: "infrastructure" },

  // INTEGRATIONS (4x)
  { code: "4A", name: "CLUES Product Suite", description: "CLUES Intelligence, London Tech Map, LifeScore app integrations", sortOrder: 18, category: "integration" },
  { code: "4B", name: "Report Generation", description: "Gamma, PDF/PPTX, client reports, market FAQs", sortOrder: 19, category: "integration" },
  { code: "4C", name: "CRM & Outreach", description: "HubSpot, Resend, Instantly, email automation", sortOrder: 20, category: "integration" },
  { code: "4D", name: "Calendar & Scheduling", description: "Nylas, meeting prep, availability management", sortOrder: 21, category: "integration" },
  { code: "4E", name: "External Data APIs", description: "Third-party data providers, government APIs, market feeds", sortOrder: 22, category: "integration" },
];

// ─────────────────────────────────────────────
// All 250 Agent Definitions
// ─────────────────────────────────────────────

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  // ═══════════════════════════════════════════
  // GROUP 1A — Olivia™ Client Interaction
  // ═══════════════════════════════════════════
  { agentId: "O1-001", name: "Client Intake Orchestrator", description: "Manages initial client onboarding, collects biographical data, initiates paragraphical extraction", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.6, defaultMaxTokens: 4096, defaultSchedule: "on_demand", persona: "olivia", capabilities: ["intake_flow", "data_collection", "persona_routing"], dataSources: ["user_input", "crm_data"], outputTypes: ["client_profile", "intake_summary"] },
  { agentId: "O1-002", name: "Conversational Flow Manager", description: "Maintains natural dialogue flow, manages turn-taking, handles interruptions gracefully", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.7, defaultMaxTokens: 4096, defaultSchedule: "realtime", persona: "olivia", capabilities: ["turn_management", "barge_in_handling", "context_tracking"], dataSources: ["conversation_history", "memory"], outputTypes: ["response", "flow_state"] },
  { agentId: "O1-003", name: "Video Response Generator", description: "Generates video responses using Simli avatar with synchronized speech and gestures", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 2048, defaultSchedule: "on_demand", persona: "olivia", capabilities: ["video_generation", "gesture_sync", "emotion_expression"], dataSources: ["response_text", "emotion_state"], outputTypes: ["video_clip", "audio_stream"] },
  { agentId: "O1-004", name: "Question Clarifier", description: "Handles ambiguous user queries, asks follow-up questions, ensures understanding", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.6, defaultMaxTokens: 2048, defaultSchedule: "realtime", persona: "olivia", capabilities: ["clarification", "disambiguation", "intent_extraction"], dataSources: ["user_query", "context"], outputTypes: ["clarifying_question", "refined_intent"] },
  { agentId: "O1-005", name: "Empathy Response Engine", description: "Detects emotional cues, generates empathetic responses, maintains warm professional tone", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.7, defaultMaxTokens: 2048, defaultSchedule: "realtime", persona: "olivia", capabilities: ["emotion_detection", "empathy_generation", "tone_adjustment"], dataSources: ["user_input", "sentiment_analysis"], outputTypes: ["empathetic_response"] },
  { agentId: "O1-006", name: "Multilingual Interpreter", description: "Real-time translation and cultural adaptation for international clients", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "realtime", persona: "olivia", capabilities: ["translation", "cultural_adaptation", "idiom_handling"], dataSources: ["user_input", "language_detection"], outputTypes: ["translated_response"], cascadePosition: 9 },
  { agentId: "O1-007", name: "Progress Narrator", description: "Explains where client is in their journey, what's been accomplished, what's next", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 2048, defaultSchedule: "on_demand", persona: "olivia", capabilities: ["journey_tracking", "progress_summary", "next_steps"], dataSources: ["journey_snapshot", "procedural_memory"], outputTypes: ["progress_update"] },
  { agentId: "O1-008", name: "Objection Handler", description: "Addresses client concerns, provides reassurance, overcomes hesitation", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.6, defaultMaxTokens: 2048, defaultSchedule: "realtime", persona: "olivia", capabilities: ["objection_detection", "reassurance", "value_articulation"], dataSources: ["user_input", "objection_library"], outputTypes: ["rebuttal", "clarification"] },
  { agentId: "O1-009", name: "Meeting Scheduler", description: "Coordinates meeting times, handles timezone conversions, sends calendar invites", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "on_demand", persona: "olivia", capabilities: ["scheduling", "timezone_handling", "calendar_integration"], dataSources: ["availability", "client_preferences"], outputTypes: ["meeting_invite", "confirmation"] },
  { agentId: "O1-010", name: "Document Explainer", description: "Walks clients through complex documents, explains terms, answers questions", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", persona: "olivia", capabilities: ["document_analysis", "term_explanation", "guided_walkthrough"], dataSources: ["document_content", "legal_glossary"], outputTypes: ["explanation", "summary"] },
  { agentId: "O1-011", name: "Follow-Up Initiator", description: "Proactively reaches out to clients, reminds of pending actions, maintains engagement", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 2048, defaultSchedule: "daily", persona: "olivia", capabilities: ["follow_up_scheduling", "reminder_generation", "engagement_tracking"], dataSources: ["client_timeline", "pending_actions"], outputTypes: ["follow_up_message", "reminder"] },
  { agentId: "O1-012", name: "Sentiment Tracker", description: "Monitors client satisfaction throughout interaction, flags concerns", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 1024, defaultSchedule: "realtime", persona: "olivia", capabilities: ["sentiment_analysis", "satisfaction_scoring", "concern_flagging"], dataSources: ["conversation_turns", "tone_analysis"], outputTypes: ["sentiment_score", "alert"] },
  { agentId: "O1-013", name: "Handoff Coordinator", description: "Manages transitions between Olivia, Cristiano, and Emelia personas", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 2048, defaultSchedule: "on_demand", persona: "olivia", capabilities: ["persona_routing", "context_transfer", "handoff_narration"], dataSources: ["conversation_state", "routing_rules"], outputTypes: ["handoff_package", "transition_message"] },
  { agentId: "O1-014", name: "Voice Tone Calibrator", description: "Adjusts Olivia's vocal characteristics based on context and client preferences", groupCode: "1A", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 1024, defaultSchedule: "realtime", persona: "olivia", capabilities: ["tone_adjustment", "pace_control", "warmth_calibration"], dataSources: ["client_profile", "context"], outputTypes: ["voice_parameters"] },

  // ═══════════════════════════════════════════
  // GROUP 1B — Cristiano™ Judge System
  // ═══════════════════════════════════════════
  { agentId: "O1-015", name: "City Match Judge", description: "Renders final verdict on optimal city matches using Opus 4.6 reasoning", groupCode: "1B", defaultModel: "claude-opus-4-6", defaultTemperature: 0.2, defaultMaxTokens: 8192, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["city_evaluation", "verdict_rendering", "rationale_generation"], dataSources: ["smart_scores", "client_profile", "city_data"], outputTypes: ["verdict", "rationale"], cascadePosition: 8 },
  { agentId: "O1-016", name: "Financial Package Judge", description: "Final approval on mortgage recommendations, investment strategies, affordability", groupCode: "1B", defaultModel: "claude-opus-4-6", defaultTemperature: 0.2, defaultMaxTokens: 8192, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["financial_verdict", "risk_assessment", "recommendation_approval"], dataSources: ["financial_analysis", "client_financials"], outputTypes: ["financial_verdict", "risk_report"], cascadePosition: 8 },
  { agentId: "O1-017", name: "LifeScore Verdict Renderer", description: "Final judgment on life optimization recommendations and wellness scores", groupCode: "1B", defaultModel: "claude-opus-4-6", defaultTemperature: 0.2, defaultMaxTokens: 8192, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["lifescore_judgment", "optimization_verdict", "wellness_assessment"], dataSources: ["lifescore_data", "module_scores"], outputTypes: ["lifescore_verdict"], cascadePosition: 8 },
  { agentId: "O1-018", name: "Contradiction Resolver", description: "Resolves conflicting information from multiple LLM passes in the cascade", groupCode: "1B", defaultModel: "claude-opus-4-6", defaultTemperature: 0.1, defaultMaxTokens: 4096, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["conflict_resolution", "truth_determination", "source_arbitration"], dataSources: ["cascade_outputs", "source_citations"], outputTypes: ["resolved_answer", "confidence_score"], cascadePosition: 8 },
  { agentId: "O1-019", name: "Quality Assurance Judge", description: "Final review of all client-facing outputs before delivery", groupCode: "1B", defaultModel: "claude-opus-4-6", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["quality_review", "accuracy_check", "compliance_verification"], dataSources: ["output_draft", "compliance_rules"], outputTypes: ["approval", "revision_request"], cascadePosition: 8 },
  { agentId: "O1-020", name: "Escalation Arbitrator", description: "Handles escalated decisions that require authoritative judgment", groupCode: "1B", defaultModel: "claude-opus-4-6", defaultTemperature: 0.2, defaultMaxTokens: 8192, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["escalation_handling", "decision_making", "authority_rendering"], dataSources: ["escalation_context", "policy_rules"], outputTypes: ["decision", "rationale"], cascadePosition: 8 },
  { agentId: "O1-021", name: "Verdict Video Generator", description: "Creates authoritative Cristiano video presentations for final verdicts", groupCode: "1B", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["verdict_presentation", "video_generation", "authority_tone"], dataSources: ["verdict_content", "client_context"], outputTypes: ["verdict_video"] },
  { agentId: "O1-022", name: "Risk Assessment Judge", description: "Evaluates risk factors in recommendations, flags high-risk scenarios", groupCode: "1B", defaultModel: "claude-opus-4-6", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", persona: "cristiano", capabilities: ["risk_evaluation", "scenario_analysis", "warning_generation"], dataSources: ["recommendation_data", "risk_factors"], outputTypes: ["risk_assessment", "warnings"], cascadePosition: 8 },

  // ═══════════════════════════════════════════
  // GROUP 1C — Emelia™ Support Operations
  // ═══════════════════════════════════════════
  { agentId: "O1-023", name: "Technical Support Agent", description: "Handles technical issues, troubleshooting, platform guidance", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", persona: "emelia", capabilities: ["troubleshooting", "technical_guidance", "issue_resolution"], dataSources: ["knowledge_base", "error_logs"], outputTypes: ["solution", "guidance"] },
  { agentId: "O1-024", name: "Knowledge Base Manager", description: "Maintains and updates internal knowledge base, surfaces relevant articles", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "daily", persona: "emelia", capabilities: ["kb_management", "article_retrieval", "content_updates"], dataSources: ["knowledge_base", "usage_analytics"], outputTypes: ["kb_article", "update_report"] },
  { agentId: "O1-025", name: "FAQ Generator", description: "Identifies common questions, generates and updates FAQ content", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 4096, defaultSchedule: "weekly", persona: "emelia", capabilities: ["faq_generation", "pattern_detection", "content_creation"], dataSources: ["conversation_logs", "support_tickets"], outputTypes: ["faq_entries"] },
  { agentId: "O1-026", name: "Ticket Router", description: "Categorizes and routes support requests to appropriate handlers", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 1024, defaultSchedule: "realtime", persona: "emelia", capabilities: ["ticket_classification", "priority_assessment", "routing"], dataSources: ["ticket_content", "routing_rules"], outputTypes: ["routed_ticket", "priority_score"] },
  { agentId: "O1-027", name: "System Status Reporter", description: "Monitors system health, generates status reports, alerts on issues", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "hourly", persona: "emelia", capabilities: ["health_monitoring", "status_reporting", "alerting"], dataSources: ["system_metrics", "error_logs"], outputTypes: ["status_report", "alert"] },
  { agentId: "O1-028", name: "Documentation Writer", description: "Creates and maintains technical documentation, user guides", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 8192, defaultSchedule: "on_demand", persona: "emelia", capabilities: ["documentation", "guide_creation", "technical_writing"], dataSources: ["codebase", "feature_specs"], outputTypes: ["documentation", "user_guide"] },
  { agentId: "O1-029", name: "Training Content Creator", description: "Develops training materials for new features and workflows", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 4096, defaultSchedule: "on_demand", persona: "emelia", capabilities: ["training_content", "tutorial_creation", "walkthrough_generation"], dataSources: ["feature_docs", "user_feedback"], outputTypes: ["training_module", "tutorial"] },
  { agentId: "O1-030", name: "Feedback Aggregator", description: "Collects and synthesizes user feedback, identifies improvement opportunities", groupCode: "1C", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "daily", persona: "emelia", capabilities: ["feedback_analysis", "trend_detection", "recommendation_generation"], dataSources: ["feedback_data", "usage_metrics"], outputTypes: ["feedback_report", "recommendations"] },

  // ═══════════════════════════════════════════
  // GROUP 1D — Persona Orchestration
  // ═══════════════════════════════════════════
  { agentId: "O1-031", name: "Persona Router", description: "Determines which persona should handle each interaction based on context", groupCode: "1D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 1024, defaultSchedule: "realtime", capabilities: ["persona_selection", "context_analysis", "routing_logic"], dataSources: ["conversation_context", "routing_rules"], outputTypes: ["persona_assignment", "routing_rationale"] },
  { agentId: "O1-032", name: "Context Preserver", description: "Maintains context across persona transitions, ensures continuity", groupCode: "1D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "realtime", capabilities: ["context_preservation", "state_management", "continuity_assurance"], dataSources: ["conversation_state", "memory_layers"], outputTypes: ["preserved_context", "transition_summary"] },
  { agentId: "O1-033", name: "Cascade Orchestrator", description: "Manages the 9-model cascade execution, routes to appropriate models", groupCode: "1D", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["cascade_routing", "model_selection", "output_aggregation"], dataSources: ["query_analysis", "model_capabilities"], outputTypes: ["cascade_plan", "aggregated_response"] },
  { agentId: "O1-034", name: "Load Balancer", description: "Distributes work across agents, prevents overload, manages queues", groupCode: "1D", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 1024, defaultSchedule: "realtime", capabilities: ["load_distribution", "queue_management", "throttling"], dataSources: ["agent_status", "queue_depths"], outputTypes: ["assignment", "queue_update"] },
  { agentId: "O1-035", name: "Fallback Handler", description: "Manages graceful degradation when primary agents fail", groupCode: "1D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["fallback_routing", "error_recovery", "graceful_degradation"], dataSources: ["error_context", "fallback_rules"], outputTypes: ["fallback_response", "recovery_plan"] },

  // ═══════════════════════════════════════════
  // GROUP 2A — CLUES Questionnaire Engine
  // ═══════════════════════════════════════════
  { agentId: "O2-001", name: "Paragraphical Extractor", description: "Extracts 100-250 metrics from 30 biographical paragraphs using Gemini", groupCode: "2A", defaultModel: "gemini-3.1-pro", defaultTemperature: 0.3, defaultMaxTokens: 16384, defaultSchedule: "on_demand", capabilities: ["paragraph_analysis", "metric_extraction", "structured_output"], dataSources: ["user_paragraphs", "extraction_prompts"], outputTypes: ["extracted_metrics", "confidence_scores"], cascadePosition: 1 },
  { agentId: "O2-002", name: "Adaptive Question Selector", description: "CAT-based question selection for optimal MOE with minimum questions", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["cat_algorithm", "question_selection", "moe_optimization"], dataSources: ["user_responses", "question_bank", "irt_parameters"], outputTypes: ["next_questions", "moe_estimate"] },
  { agentId: "O2-003", name: "Module Relevance Engine", description: "Determines which of 23 specialty modules are relevant for each user", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["module_matching", "relevance_scoring", "pathway_optimization"], dataSources: ["user_profile", "module_definitions"], outputTypes: ["relevant_modules", "relevance_scores"] },
  { agentId: "O2-004", name: "Demographics Analyzer", description: "Processes 34 demographics questions, builds baseline profile", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["demographics_analysis", "profile_building", "baseline_establishment"], dataSources: ["demographics_responses"], outputTypes: ["demographic_profile"] },
  { agentId: "O2-005", name: "Dealbreaker Detector", description: "Identifies absolute non-negotiables from 33 DNW questions", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["dealbreaker_detection", "constraint_extraction", "hard_filter_creation"], dataSources: ["dnw_responses"], outputTypes: ["dealbreakers", "hard_constraints"] },
  { agentId: "O2-006", name: "Must-Have Identifier", description: "Extracts critical requirements from 33 must-have questions", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["must_have_extraction", "requirement_prioritization"], dataSources: ["must_have_responses"], outputTypes: ["requirements", "priority_weights"] },
  { agentId: "O2-007", name: "Tradeoff Analyzer", description: "Processes 50 tradeoff questions, builds preference matrix", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["tradeoff_analysis", "preference_modeling", "weight_calculation"], dataSources: ["tradeoff_responses"], outputTypes: ["preference_matrix", "tradeoff_weights"] },
  { agentId: "O2-008", name: "General Question Processor", description: "Handles 50 general lifestyle and preference questions", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["lifestyle_analysis", "preference_extraction"], dataSources: ["general_responses"], outputTypes: ["lifestyle_profile"] },
  { agentId: "O2-009", name: "Specialty Module Runner", description: "Executes specialty module questionnaires (~100Q each)", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["module_execution", "specialized_questioning"], dataSources: ["module_questions", "user_responses"], outputTypes: ["module_scores", "detailed_analysis"] },
  { agentId: "O2-010", name: "Response Validator", description: "Validates questionnaire responses, detects inconsistencies", groupCode: "2A", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["response_validation", "inconsistency_detection", "clarification_triggering"], dataSources: ["all_responses", "validation_rules"], outputTypes: ["validation_report", "clarification_requests"] },

  // ═══════════════════════════════════════════
  // GROUP 2B — SMART Score™ Calculation
  // ═══════════════════════════════════════════
  { agentId: "O2-011", name: "City Evaluator Primary", description: "Primary city evaluation using Claude Sonnet 4.6", groupCode: "2B", defaultModel: "claude-sonnet-4-6", defaultTemperature: 0.4, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["city_evaluation", "factor_weighting", "score_calculation"], dataSources: ["city_data", "user_profile", "smart_weights"], outputTypes: ["city_scores", "evaluation_report"], cascadePosition: 2 },
  { agentId: "O2-012", name: "City Evaluator Secondary", description: "Secondary city evaluation using GPT-5.4 for validation", groupCode: "2B", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["city_validation", "cross_verification", "discrepancy_detection"], dataSources: ["city_data", "user_profile", "primary_scores"], outputTypes: ["validation_scores", "discrepancies"], cascadePosition: 3 },
  { agentId: "O2-013", name: "Verification Engine", description: "Gemini verification pass with Google Search integration", groupCode: "2B", defaultModel: "gemini-3.1-pro", defaultTemperature: 0.3, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["fact_verification", "search_integration", "data_validation"], dataSources: ["evaluation_outputs", "google_search"], outputTypes: ["verified_data", "correction_suggestions"], cascadePosition: 4 },
  { agentId: "O2-014", name: "Math Specialist", description: "Grok 4 for complex mathematical calculations and equations", groupCode: "2B", defaultModel: "grok-4", defaultTemperature: 0.1, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["mathematical_computation", "equation_solving", "statistical_analysis"], dataSources: ["calculation_requests", "raw_data"], outputTypes: ["computed_values", "statistical_outputs"], cascadePosition: 5 },
  { agentId: "O2-015", name: "Citation Generator", description: "Perplexity Sonar for sourced answers with citations", groupCode: "2B", defaultModel: "sonar-pro", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["citation_generation", "source_attribution", "fact_sourcing"], dataSources: ["research_queries"], outputTypes: ["cited_answers", "source_list"], cascadePosition: 6 },
  { agentId: "O2-016", name: "Web Research Agent", description: "Tavily MCP for real-time web research", groupCode: "2B", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["web_search", "current_data_retrieval", "trend_detection"], dataSources: ["search_queries"], outputTypes: ["search_results", "current_data"], cascadePosition: 7 },
  { agentId: "O2-017", name: "Comparison Generator", description: "Creates detailed city-to-city comparison reports", groupCode: "2B", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["comparison_generation", "visualization_prep", "narrative_creation"], dataSources: ["city_scores", "user_priorities"], outputTypes: ["comparison_report", "visualizations"] },
  { agentId: "O2-018", name: "Neighborhood Scorer", description: "Scores neighborhoods within selected cities", groupCode: "2B", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["neighborhood_analysis", "micro_scoring", "hyperlocal_data"], dataSources: ["neighborhood_data", "user_preferences"], outputTypes: ["neighborhood_scores", "rankings"] },
  { agentId: "O2-019", name: "Output Formatter", description: "Formats SMART Score outputs for reports and presentations", groupCode: "2B", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["output_formatting", "report_structure", "visualization_generation"], dataSources: ["raw_scores", "template_library"], outputTypes: ["formatted_report", "charts"] },

  // ═══════════════════════════════════════════
  // GROUP 2C — LifeScore Integration
  // ═══════════════════════════════════════════
  { agentId: "O2-020", name: "LifeScore Orchestrator", description: "Coordinates all 20 LifeScore module apps", groupCode: "2C", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["module_orchestration", "score_aggregation", "pathway_management"], dataSources: ["module_data", "user_progress"], outputTypes: ["aggregated_score", "module_status"] },
  { agentId: "O2-021", name: "Health Module Agent", description: "Processes health and wellness questionnaire module", groupCode: "2C", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["health_assessment", "wellness_scoring"], dataSources: ["health_responses"], outputTypes: ["health_score", "recommendations"] },
  { agentId: "O2-022", name: "Wealth Module Agent", description: "Processes financial health and wealth building module", groupCode: "2C", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["wealth_assessment", "financial_scoring"], dataSources: ["financial_responses"], outputTypes: ["wealth_score", "financial_plan"] },
  { agentId: "O2-023", name: "Relationships Module Agent", description: "Processes relationship satisfaction and social health module", groupCode: "2C", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["relationship_assessment", "social_scoring"], dataSources: ["relationship_responses"], outputTypes: ["relationship_score", "social_recommendations"] },
  { agentId: "O2-024", name: "Career Module Agent", description: "Processes career satisfaction and growth module", groupCode: "2C", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["career_assessment", "growth_scoring"], dataSources: ["career_responses"], outputTypes: ["career_score", "growth_plan"] },
  { agentId: "O2-025", name: "Purpose Module Agent", description: "Processes life purpose and meaning module", groupCode: "2C", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["purpose_assessment", "meaning_scoring"], dataSources: ["purpose_responses"], outputTypes: ["purpose_score", "alignment_report"] },

  // ═══════════════════════════════════════════
  // GROUP 2D — Real Estate Intelligence
  // ═══════════════════════════════════════════
  { agentId: "O2-030", name: "MLS Data Aggregator", description: "Aggregates and normalizes MLS data from RESO Web API", groupCode: "2D", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "daily", capabilities: ["mls_integration", "data_normalization", "listing_aggregation"], dataSources: ["mls_reso_api"], outputTypes: ["normalized_listings", "market_summary"] },
  { agentId: "O2-031", name: "Property Valuation Agent", description: "Calculates AVMs using HouseCanary and Plunk AI", groupCode: "2D", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["avm_calculation", "valuation_analysis", "confidence_scoring"], dataSources: ["housecanary_api", "plunk_api", "property_data"], outputTypes: ["valuation_report", "confidence_interval"] },
  { agentId: "O2-032", name: "Rental Analysis Agent", description: "Estimates rental values and investment potential using Rentcast", groupCode: "2D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["rental_estimation", "investment_analysis", "yield_calculation"], dataSources: ["rentcast_api", "property_data"], outputTypes: ["rental_estimate", "investment_report"] },
  { agentId: "O2-033", name: "Neighborhood Intelligence Agent", description: "Compiles neighborhood profiles from multiple data sources", groupCode: "2D", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["neighborhood_profiling", "data_compilation", "score_calculation"], dataSources: ["crime_data", "school_data", "amenity_data"], outputTypes: ["neighborhood_profile", "composite_score"] },
  { agentId: "O2-034", name: "Market Trend Analyzer", description: "Analyzes market trends and forecasts price movements", groupCode: "2D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "weekly", capabilities: ["trend_analysis", "price_forecasting", "market_timing"], dataSources: ["historical_data", "market_indicators"], outputTypes: ["trend_report", "forecast"] },
  { agentId: "O2-035", name: "Property Match Agent", description: "Matches client requirements to available properties", groupCode: "2D", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["property_matching", "requirement_filtering", "ranking"], dataSources: ["client_requirements", "listing_data"], outputTypes: ["matched_properties", "match_scores"] },

  // ═══════════════════════════════════════════
  // GROUP 2E — Relocation Intelligence
  // ═══════════════════════════════════════════
  { agentId: "O2-040", name: "Cost of Living Calculator", description: "Calculates detailed cost of living comparisons", groupCode: "2E", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["col_calculation", "city_comparison", "budget_modeling"], dataSources: ["wherenext_api", "open_exchange_rates"], outputTypes: ["col_report", "budget_comparison"] },
  { agentId: "O2-041", name: "Transit Score Agent", description: "Evaluates transit options and walkability", groupCode: "2E", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["transit_scoring", "walkability_analysis", "commute_calculation"], dataSources: ["walkscore_api", "google_maps"], outputTypes: ["transit_score", "commute_analysis"] },
  { agentId: "O2-042", name: "Safety Analyzer", description: "Analyzes crime data and safety metrics", groupCode: "2E", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["crime_analysis", "safety_scoring", "trend_detection"], dataSources: ["fbi_crime_api", "local_crime_data"], outputTypes: ["safety_score", "crime_report"] },
  { agentId: "O2-043", name: "School District Analyzer", description: "Evaluates school districts and educational quality", groupCode: "2E", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["school_evaluation", "district_ranking", "program_matching"], dataSources: ["schooldigger_api", "education_data"], outputTypes: ["school_report", "rankings"] },
  { agentId: "O2-044", name: "Environmental Risk Agent", description: "Assesses environmental risks: floods, storms, air quality", groupCode: "2E", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["risk_assessment", "environmental_scoring"], dataSources: ["fema_api", "noaa_api", "airnow_api"], outputTypes: ["risk_report", "environmental_score"] },
  { agentId: "O2-045", name: "Healthcare Access Agent", description: "Evaluates healthcare access and quality", groupCode: "2E", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["healthcare_evaluation", "access_scoring"], dataSources: ["cms_data", "hospital_data"], outputTypes: ["healthcare_score", "facility_list"] },

  // ═══════════════════════════════════════════
  // GROUP 2F — Financial Analysis
  // ═══════════════════════════════════════════
  { agentId: "O2-050", name: "Mortgage Calculator", description: "Calculates mortgage payments, affordability, scenarios", groupCode: "2F", defaultModel: "gpt-4o", defaultTemperature: 0.1, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["mortgage_calculation", "scenario_modeling", "affordability_analysis"], dataSources: ["rate_data", "client_financials"], outputTypes: ["payment_schedule", "affordability_report"] },
  { agentId: "O2-051", name: "Investment Analyzer", description: "Analyzes real estate investment potential", groupCode: "2F", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["investment_analysis", "roi_calculation", "risk_assessment"], dataSources: ["property_data", "market_data"], outputTypes: ["investment_report", "roi_projections"] },
  { agentId: "O2-052", name: "Tax Impact Calculator", description: "Estimates property tax and income tax implications", groupCode: "2F", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["tax_calculation", "deduction_analysis", "jurisdiction_comparison"], dataSources: ["tax_data", "property_data"], outputTypes: ["tax_estimate", "comparison_report"] },

  // ═══════════════════════════════════════════
  // GROUP 2G — Immigration & Visa
  // ═══════════════════════════════════════════
  { agentId: "O2-060", name: "Visa Requirement Agent", description: "Determines visa requirements for destination countries", groupCode: "2G", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["visa_lookup", "requirement_analysis", "pathway_mapping"], dataSources: ["travel_buddy_api", "immigration_data"], outputTypes: ["visa_requirements", "pathway_options"] },
  { agentId: "O2-061", name: "Immigration Pathway Advisor", description: "Advises on immigration pathways and timelines", groupCode: "2G", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["pathway_analysis", "timeline_estimation", "document_checklist"], dataSources: ["immigration_rules", "client_profile"], outputTypes: ["pathway_report", "timeline", "checklist"] },

  // ═══════════════════════════════════════════
  // GROUP 2H — Pitch Intelligence
  // ═══════════════════════════════════════════
  { agentId: "O2-070", name: "Archetype Matcher", description: "Scores and matches 75 pitch deck archetypes to founder profile, stage, and industry", groupCode: "2H", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["archetype_matching", "scoring", "recommendation"], dataSources: ["founder_profile", "deck_archetypes"], outputTypes: ["matched_archetypes", "scores", "rationale"] },
  { agentId: "O2-071", name: "Template Scorer", description: "Scores 12 business plan templates for optimal fit based on stage and industry", groupCode: "2H", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["template_scoring", "recommendation", "fit_analysis"], dataSources: ["founder_profile", "plan_templates"], outputTypes: ["scored_templates", "recommendations"] },
  { agentId: "O2-072", name: "Slide Optimizer", description: "LLM-powered slide optimization with persona-aware rewriting and confidence scoring", groupCode: "2H", defaultModel: "claude-sonnet-4-6", defaultTemperature: 0.4, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["slide_rewriting", "confidence_scoring", "persona_adaptation"], dataSources: ["slide_content", "persona_config"], outputTypes: ["optimized_slide", "confidence_score", "change_notes"] },
  { agentId: "O2-073", name: "Plan Section Drafter", description: "Drafts business plan sections with web search verification and fact-checking", groupCode: "2H", defaultModel: "claude-sonnet-4-6", defaultTemperature: 0.5, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["section_drafting", "fact_verification", "web_search"], dataSources: ["section_requirements", "company_data"], outputTypes: ["drafted_section", "confidence_score", "sources"] },
  { agentId: "O2-074", name: "Content Analyzer", description: "Analyzes pitch/plan content for investor readiness with London ecosystem context", groupCode: "2H", defaultModel: "claude-sonnet-4-6", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["content_analysis", "investor_readiness", "london_fit_assessment"], dataSources: ["content", "investor_criteria"], outputTypes: ["analysis_report", "suggestions", "warnings"] },
  { agentId: "O2-075", name: "Persona Adapter", description: "Adapts content style and metrics for 5 investor personas (Angel, Seed VC, Series A, Strategic, Buyout)", groupCode: "2H", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["persona_adaptation", "tone_adjustment", "metric_selection"], dataSources: ["content", "persona_profiles"], outputTypes: ["adapted_content", "tone_recommendations"] },
  { agentId: "O2-076", name: "Deck Score Calculator", description: "Calculates composite deck scores: clarity, impact, and moat metrics", groupCode: "2H", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["score_calculation", "metric_aggregation", "benchmark_comparison"], dataSources: ["deck_slides", "scoring_rubric"], outputTypes: ["deck_scores", "dimension_breakdown"] },
  { agentId: "O2-077", name: "Document Generator", description: "Generates fundraising documents from 10 categories (investor, legal, tech, market, team, etc.)", groupCode: "2H", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["document_generation", "template_population", "formatting"], dataSources: ["company_data", "document_templates"], outputTypes: ["generated_document", "completion_status"] },
  { agentId: "O2-078", name: "Theme Applicator", description: "Applies 5 London-branded visual themes to pitch outputs (Canary-Sapphire, Gherkin-Polished, etc.)", groupCode: "2H", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 1024, defaultSchedule: "on_demand", capabilities: ["theme_application", "style_consistency", "brand_adaptation"], dataSources: ["content", "theme_definitions"], outputTypes: ["themed_output", "style_tokens"] },
  { agentId: "O2-079", name: "Pitch Coach Olivia", description: "Conversational pitch coaching with full archetype and template library access", groupCode: "2H", defaultModel: "claude-sonnet-4-6", defaultTemperature: 0.6, defaultMaxTokens: 2048, defaultSchedule: "realtime", persona: "olivia", capabilities: ["pitch_coaching", "question_answering", "strategy_advice"], dataSources: ["archetypes", "templates", "conversation_history"], outputTypes: ["coaching_response", "recommendations"] },

  // ═══════════════════════════════════════════
  // GROUP 3A — Memory Systems
  // ═══════════════════════════════════════════
  { agentId: "O3-001", name: "Episodic Memory Manager", description: "Creates and retrieves episodic memories from conversations", groupCode: "3A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["episode_creation", "memory_retrieval", "episode_chaining"], dataSources: ["conversation_turns", "memory_store"], outputTypes: ["episode", "relevant_memories"] },
  { agentId: "O3-002", name: "Semantic Memory Distiller", description: "Distills facts and preferences from conversations", groupCode: "3A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["fact_extraction", "preference_learning", "contradiction_detection"], dataSources: ["conversation_history", "semantic_store"], outputTypes: ["new_facts", "updated_preferences"] },
  { agentId: "O3-003", name: "Procedural Memory Learner", description: "Learns and applies procedural workflows", groupCode: "3A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["workflow_learning", "procedure_execution", "success_tracking"], dataSources: ["procedural_store", "execution_logs"], outputTypes: ["learned_procedure", "execution_result"] },
  { agentId: "O3-004", name: "Knowledge Graph Builder", description: "Builds and maintains knowledge graph entities and relationships", groupCode: "3A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["entity_extraction", "relationship_mapping", "graph_traversal"], dataSources: ["content", "graph_store"], outputTypes: ["entities", "relationships"] },
  { agentId: "O3-005", name: "Memory Consolidation Agent", description: "Consolidates and prunes memories for efficiency", groupCode: "3A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "daily", capabilities: ["memory_consolidation", "importance_scoring", "pruning"], dataSources: ["all_memory_stores"], outputTypes: ["consolidation_report"] },
  { agentId: "O3-006", name: "Journey Snapshot Manager", description: "Creates and restores journey snapshots for session resume", groupCode: "3A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["snapshot_creation", "state_restoration", "context_summarization"], dataSources: ["conversation_state", "procedure_state"], outputTypes: ["snapshot", "restored_context"] },

  // ═══════════════════════════════════════════
  // GROUP 3B — 9-Model Cascade
  // ═══════════════════════════════════════════
  { agentId: "O3-010", name: "Cascade Controller", description: "Orchestrates the full 9-model cascade execution", groupCode: "3B", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["cascade_orchestration", "model_routing", "result_aggregation"], dataSources: ["query", "model_status"], outputTypes: ["cascade_result", "execution_trace"] },
  { agentId: "O3-011", name: "Model Health Monitor", description: "Monitors health and availability of all cascade models", groupCode: "3B", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 1024, defaultSchedule: "hourly", capabilities: ["health_checking", "latency_monitoring", "fallback_routing"], dataSources: ["model_endpoints", "health_metrics"], outputTypes: ["health_status", "alerts"] },
  { agentId: "O3-012", name: "Result Aggregator", description: "Aggregates and reconciles outputs from multiple models", groupCode: "3B", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["output_aggregation", "conflict_resolution", "confidence_scoring"], dataSources: ["model_outputs"], outputTypes: ["aggregated_result", "confidence_report"] },

  // ═══════════════════════════════════════════
  // GROUP 3C — RAG Pipeline
  // ═══════════════════════════════════════════
  { agentId: "O3-020", name: "Document Ingestor", description: "Ingests documents using Firecrawl and Unstructured", groupCode: "3C", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["document_ingestion", "extraction", "chunking"], dataSources: ["firecrawl_api", "unstructured_api"], outputTypes: ["chunks", "metadata"] },
  { agentId: "O3-021", name: "Embedding Generator", description: "Generates embeddings for document chunks", groupCode: "3C", defaultModel: "gpt-4o", defaultTemperature: 0.1, defaultMaxTokens: 1024, defaultSchedule: "on_demand", capabilities: ["embedding_generation", "vector_storage"], dataSources: ["text_chunks"], outputTypes: ["embeddings"] },
  { agentId: "O3-022", name: "Retrieval Agent", description: "Retrieves relevant context using semantic search", groupCode: "3C", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["semantic_search", "context_retrieval", "reranking"], dataSources: ["query", "vector_store"], outputTypes: ["relevant_chunks", "citations"] },
  { agentId: "O3-023", name: "Citation Builder", description: "Builds citations and provenance for RAG outputs", groupCode: "3C", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["citation_generation", "source_attribution"], dataSources: ["retrieved_chunks"], outputTypes: ["citations", "provenance"] },

  // ═══════════════════════════════════════════
  // GROUP 3D — Voice & Avatar
  // ═══════════════════════════════════════════
  { agentId: "O3-030", name: "TTS Orchestrator", description: "Manages text-to-speech across ElevenLabs personas", groupCode: "3D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 1024, defaultSchedule: "on_demand", capabilities: ["tts_routing", "voice_selection", "audio_generation"], dataSources: ["text_input", "persona_config"], outputTypes: ["audio_stream"] },
  { agentId: "O3-031", name: "STT Processor", description: "Processes speech-to-text using Deepgram/Whisper", groupCode: "3D", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 1024, defaultSchedule: "realtime", capabilities: ["speech_recognition", "transcription"], dataSources: ["audio_input"], outputTypes: ["transcript"] },
  { agentId: "O3-032", name: "Avatar Controller", description: "Controls Simli/HeyGen avatar generation", groupCode: "3D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 1024, defaultSchedule: "on_demand", capabilities: ["avatar_generation", "gesture_control", "lip_sync"], dataSources: ["audio", "emotion_state"], outputTypes: ["video_stream"] },
  { agentId: "O3-033", name: "Realtime Pipeline Manager", description: "Manages STT→LLM→TTS→Avatar pipeline", groupCode: "3D", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "realtime", capabilities: ["pipeline_orchestration", "latency_optimization"], dataSources: ["audio_input", "conversation_state"], outputTypes: ["video_response"] },

  // ═══════════════════════════════════════════
  // GROUP 3E — Compliance & Safety
  // ═══════════════════════════════════════════
  { agentId: "O3-040", name: "PII Redactor", description: "Detects and redacts PII using Presidio", groupCode: "3E", defaultModel: "gpt-4o", defaultTemperature: 0.1, defaultMaxTokens: 2048, defaultSchedule: "realtime", capabilities: ["pii_detection", "redaction", "anonymization"], dataSources: ["text_input"], outputTypes: ["redacted_text", "pii_report"] },
  { agentId: "O3-041", name: "Fair Housing Validator", description: "Ensures compliance with Fair Housing regulations", groupCode: "3E", defaultModel: "gpt-4o", defaultTemperature: 0.1, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["compliance_checking", "violation_detection"], dataSources: ["content", "fair_housing_rules"], outputTypes: ["compliance_report", "violations"] },
  { agentId: "O3-042", name: "Hallucination Detector", description: "Detects potential hallucinations using NeMo Guardrails", groupCode: "3E", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["hallucination_detection", "fact_verification"], dataSources: ["llm_output", "source_data"], outputTypes: ["confidence_score", "hallucination_flags"] },
  { agentId: "O3-043", name: "Audit Logger", description: "Maintains comprehensive audit logs for compliance", groupCode: "3E", defaultModel: "gpt-4o", defaultTemperature: 0.1, defaultMaxTokens: 1024, defaultSchedule: "realtime", capabilities: ["audit_logging", "event_tracking"], dataSources: ["system_events"], outputTypes: ["audit_entry"] },

  // ═══════════════════════════════════════════
  // GROUP 3F — Observability
  // ═══════════════════════════════════════════
  { agentId: "O3-050", name: "Trace Collector", description: "Collects and stores execution traces via Langfuse", groupCode: "3F", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 1024, defaultSchedule: "realtime", capabilities: ["trace_collection", "span_recording"], dataSources: ["execution_context"], outputTypes: ["trace"] },
  { agentId: "O3-051", name: "Metric Aggregator", description: "Aggregates system metrics for dashboards", groupCode: "3F", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "hourly", capabilities: ["metric_aggregation", "trend_calculation"], dataSources: ["raw_metrics"], outputTypes: ["aggregated_metrics"] },
  { agentId: "O3-052", name: "Alert Generator", description: "Generates alerts based on metric thresholds", groupCode: "3F", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 1024, defaultSchedule: "realtime", capabilities: ["threshold_monitoring", "alert_generation"], dataSources: ["metrics", "alert_rules"], outputTypes: ["alerts"] },

  // ═══════════════════════════════════════════
  // GROUP 4A — CLUES Product Suite
  // ═══════════════════════════════════════════
  { agentId: "O4-001", name: "CLUES Intelligence Adapter", description: "Integrates with CLUES Intelligence (UK flagship)", groupCode: "4A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["clues_integration", "data_sync"], dataSources: ["clues_intelligence_api"], outputTypes: ["clues_data", "sync_status"] },
  { agentId: "O4-002", name: "London Tech Map Adapter", description: "Integrates with CLUES London Tech Map", groupCode: "4A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["ltm_integration", "district_data"], dataSources: ["clues_london_api"], outputTypes: ["london_data", "district_scores"] },
  { agentId: "O4-003", name: "LifeScore App Adapter", description: "Integrates with CLUES LifeScore (clueslifescore.com)", groupCode: "4A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["lifescore_integration", "module_sync"], dataSources: ["clues_lifescore_api"], outputTypes: ["lifescore_data"] },
  { agentId: "O4-004", name: "Stay or Sell Adapter", description: "Integrates with Stay or Sell™ Advisor (FL coastal)", groupCode: "4A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["stay_sell_integration"], dataSources: ["stay_or_sell_api"], outputTypes: ["advisory_data"] },
  { agentId: "O4-005", name: "Brokerage Stack Adapter", description: "Integrates with Tampa Bay Brokerage Stack", groupCode: "4A", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["brokerage_integration"], dataSources: ["brokerage_api"], outputTypes: ["brokerage_data"] },

  // ═══════════════════════════════════════════
  // GROUP 4B — Report Generation
  // ═══════════════════════════════════════════
  { agentId: "O4-010", name: "Gamma Report Generator", description: "Generates premium reports using Gamma AI", groupCode: "4B", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["gamma_generation", "presentation_creation"], dataSources: ["report_data", "gamma_api"], outputTypes: ["gamma_presentation", "pdf"] },
  { agentId: "O4-011", name: "Relocation Report Builder", description: "Builds 100-page client relocation reports", groupCode: "4B", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 8192, defaultSchedule: "on_demand", capabilities: ["report_compilation", "formatting"], dataSources: ["all_scores", "client_data"], outputTypes: ["relocation_report"] },
  { agentId: "O4-012", name: "Market FAQ Generator", description: "Generates per-market FAQ content", groupCode: "4B", defaultModel: "gpt-4o", defaultTemperature: 0.5, defaultMaxTokens: 4096, defaultSchedule: "weekly", capabilities: ["faq_generation", "market_research"], dataSources: ["market_data", "common_questions"], outputTypes: ["faq_content"] },
  { agentId: "O4-013", name: "Meeting Prep Packet Builder", description: "Creates client meeting preparation packets", groupCode: "4B", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["packet_generation", "agenda_creation"], dataSources: ["client_profile", "meeting_context"], outputTypes: ["prep_packet"] },

  // ═══════════════════════════════════════════
  // GROUP 4C — CRM & Outreach
  // ═══════════════════════════════════════════
  { agentId: "O4-020", name: "HubSpot Sync Agent", description: "Syncs client data with HubSpot CRM", groupCode: "4C", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "hourly", capabilities: ["hubspot_sync", "contact_management"], dataSources: ["client_data", "hubspot_api"], outputTypes: ["sync_status"] },
  { agentId: "O4-021", name: "Email Composer", description: "Composes personalized emails via Resend", groupCode: "4C", defaultModel: "gpt-4o", defaultTemperature: 0.6, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["email_composition", "personalization"], dataSources: ["client_context", "template_library"], outputTypes: ["email_draft"] },
  { agentId: "O4-022", name: "Outreach Sequence Agent", description: "Manages outbound sequences via Instantly.ai", groupCode: "4C", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 2048, defaultSchedule: "daily", capabilities: ["sequence_management", "campaign_optimization"], dataSources: ["sequence_data", "instantly_api"], outputTypes: ["sequence_status"] },

  // ═══════════════════════════════════════════
  // GROUP 4D — Calendar & Scheduling
  // ═══════════════════════════════════════════
  { agentId: "O4-030", name: "Nylas Calendar Agent", description: "Manages calendar integration via Nylas", groupCode: "4D", defaultModel: "gpt-4o", defaultTemperature: 0.3, defaultMaxTokens: 2048, defaultSchedule: "realtime", capabilities: ["calendar_sync", "availability_management"], dataSources: ["nylas_api"], outputTypes: ["availability", "events"] },
  { agentId: "O4-031", name: "Meeting Prep Agent", description: "Prepares context and materials for upcoming meetings", groupCode: "4D", defaultModel: "gpt-4o", defaultTemperature: 0.4, defaultMaxTokens: 4096, defaultSchedule: "on_demand", capabilities: ["prep_generation", "context_compilation"], dataSources: ["calendar_events", "client_data"], outputTypes: ["prep_materials"] },

  // ═══════════════════════════════════════════
  // GROUP 4E — External Data APIs
  // ═══════════════════════════════════════════
  { agentId: "O4-040", name: "Google Places Agent", description: "Fetches amenity data from Google Places API", groupCode: "4E", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["places_search", "amenity_data"], dataSources: ["google_places_api"], outputTypes: ["places_data"] },
  { agentId: "O4-041", name: "Weather Data Agent", description: "Fetches weather and climate data from OpenWeatherMap", groupCode: "4E", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "daily", capabilities: ["weather_fetch", "climate_analysis"], dataSources: ["openweathermap_api"], outputTypes: ["weather_data"] },
  { agentId: "O4-042", name: "Companies House Agent", description: "Fetches UK company data from Companies House", groupCode: "4E", defaultModel: "gpt-4o", defaultTemperature: 0.2, defaultMaxTokens: 2048, defaultSchedule: "on_demand", capabilities: ["company_lookup", "filing_data"], dataSources: ["companies_house_api"], outputTypes: ["company_data"] },
];

// ─────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────

export function getAgentDefinition(agentId: string): AgentDefinition | undefined {
  return AGENT_DEFINITIONS.find((a) => a.agentId === agentId);
}

export function getAgentsByGroup(groupCode: string): AgentDefinition[] {
  return AGENT_DEFINITIONS.filter((a) => a.groupCode === groupCode);
}

export function getAgentsByPersona(persona: string): AgentDefinition[] {
  return AGENT_DEFINITIONS.filter((a) => a.persona === persona);
}

export function getAgentsByCascadePosition(position: number): AgentDefinition[] {
  return AGENT_DEFINITIONS.filter((a) => a.cascadePosition === position);
}

export function getGroupDefinition(code: string): AgentGroupDefinition | undefined {
  return AGENT_GROUPS.find((g) => g.code === code);
}
