/**
 * OLIVIA BRAIN — Pitch Intelligence Archetypes
 *
 * 75 pitch deck archetypes from Studio-Olivia.
 * Each archetype represents a proven fundraising approach.
 */

import type { PitchDeckArchetype, DeckCategory } from "./types";

// ─────────────────────────────────────────────
// 75 Pitch Deck Archetypes
// ─────────────────────────────────────────────

export const DECKS: PitchDeckArchetype[] = [
  // ── CLASSIC DECKS (1-10) ──
  {
    id: 1,
    name: "Airbnb",
    tag: "Minimalist Masterclass",
    cat: "classic",
    stage: ["Seed"],
    consensus: 4,
    insight: "Clarity beat polish. Ten words per slide.",
    fit: "London B2C founders who need to strip their deck to its essential claim.",
    olivia_action: "Strip fluff, enforce clarity — removes any slide that cannot survive a ten-word summary.",
    year: 2008,
    slideCount: 11,
    raised: "$600K",
  },
  {
    id: 2,
    name: "Uber",
    tag: "Vision-First Disruption",
    cat: "classic",
    stage: ["Seed"],
    consensus: 4,
    insight: "Lead with the vision of the world you're creating, not the product.",
    fit: "Founders disrupting regulated industries who need to paint the future.",
    olivia_action: "Reframe product slides as vision slides — 'what the world looks like when we win'.",
    year: 2008,
    slideCount: 25,
    raised: "$1.5M",
  },
  {
    id: 3,
    name: "Buffer",
    tag: "Traction Transparency",
    cat: "saas",
    stage: ["Seed"],
    consensus: 4,
    insight: "Radical transparency on metrics builds trust. Share everything.",
    fit: "SaaS founders with strong metrics who can afford full transparency.",
    olivia_action: "Add dashboard screenshots with real numbers — hide nothing.",
    year: 2011,
    slideCount: 13,
    raised: "$500K",
  },
  {
    id: 4,
    name: "LinkedIn",
    tag: "Network Effects",
    cat: "classic",
    stage: ["Series A"],
    consensus: 4,
    insight: "Explain the flywheel. Show how each user adds value for the next.",
    fit: "Marketplace and network-effect businesses.",
    olivia_action: "Add network flywheel diagram showing value amplification.",
    year: 2004,
    slideCount: 15,
    raised: "$4.7M",
  },
  {
    id: 5,
    name: "Facebook",
    tag: "Campus-First Growth",
    cat: "classic",
    stage: ["Seed"],
    consensus: 4,
    insight: "Density beats breadth. Own one niche before expanding.",
    fit: "Consumer startups with clear initial beachhead market.",
    olivia_action: "Define your 'campus' — the first market you'll dominate.",
    year: 2004,
    slideCount: 10,
    raised: "$500K",
  },
  {
    id: 6,
    name: "YouTube",
    tag: "Platform Vision",
    cat: "classic",
    stage: ["Seed"],
    consensus: 3,
    insight: "Position as infrastructure, not content.",
    fit: "Platform plays where the value is enabling others.",
    olivia_action: "Reframe as 'X for Y' platform positioning.",
    year: 2005,
    slideCount: 12,
  },
  {
    id: 7,
    name: "Dropbox",
    tag: "Product Demo First",
    cat: "saas",
    stage: ["Seed"],
    consensus: 5,
    insight: "A 3-minute video can replace 30 slides. Show, don't tell.",
    fit: "Product-led growth companies with obvious UX.",
    olivia_action: "Add demo video link or GIF showing core workflow.",
    year: 2007,
    slideCount: 8,
    raised: "$1.2M",
  },
  {
    id: 8,
    name: "Mint",
    tag: "Category Creation",
    cat: "fintech",
    stage: ["Seed"],
    consensus: 4,
    insight: "Create a new category name. Own the language.",
    fit: "Fintech founders creating new financial product categories.",
    olivia_action: "Define your category name and own the terminology.",
    year: 2006,
    slideCount: 14,
    raised: "$750K",
  },
  {
    id: 9,
    name: "Square",
    tag: "Hardware + Software",
    cat: "fintech",
    stage: ["Seed"],
    consensus: 4,
    insight: "Physical products need to tell a story about why they exist.",
    fit: "Hardware-enabled software companies.",
    olivia_action: "Lead with the physical product image — hardware tells the story.",
    year: 2009,
    slideCount: 16,
    raised: "$10M",
  },
  {
    id: 10,
    name: "Slack",
    tag: "Internal Tool → Product",
    cat: "saas",
    stage: ["Seed"],
    consensus: 4,
    insight: "Built for ourselves first. Dog-fooded to perfection.",
    fit: "B2B tools that started as internal solutions.",
    olivia_action: "Tell the 'built for ourselves' origin story.",
    year: 2013,
    slideCount: 12,
    raised: "$1.5M",
  },

  // ── VC FRAMEWORKS (11-20) ──
  {
    id: 11,
    name: "Sequoia",
    tag: "Universal 11-Slide",
    cat: "vc_framework",
    stage: ["Any"],
    consensus: 5,
    insight: "Company Purpose → Problem → Solution → Why Now → Market → Competition → Product → Business Model → Team → Financials → Ask",
    fit: "Default for any London founder raising institutional capital.",
    olivia_action: "Auto-generate all 11 sections from Company DNA.",
    slideCount: 11,
  },
  {
    id: 12,
    name: "Y Combinator",
    tag: "2.5-Min Demo Day",
    cat: "vc_framework",
    stage: ["Pre-seed", "Seed"],
    consensus: 5,
    insight: "Problem → Solution → Traction → Ask. Everything else is noise.",
    fit: "Early-stage founders who need to cut to the chase.",
    olivia_action: "Strip to 4 core slides — ruthless simplicity.",
    slideCount: 8,
  },
  {
    id: 13,
    name: "Guy Kawasaki",
    tag: "10/20/30 Rule",
    cat: "vc_framework",
    stage: ["Any"],
    consensus: 4,
    insight: "10 slides, 20 minutes, 30pt font minimum. Constraints breed clarity.",
    fit: "Founders who tend to over-explain.",
    olivia_action: "Enforce 10-slide limit and minimum font size.",
    slideCount: 10,
  },
  {
    id: 14,
    name: "a16z",
    tag: "Narrative Arc",
    cat: "vc_framework",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Tell a story with beginning, middle, end. Investors remember narratives.",
    fit: "Later-stage founders with complex products.",
    olivia_action: "Structure as 3-act narrative arc.",
    slideCount: 15,
  },
  {
    id: 15,
    name: "Index Ventures",
    tag: "European Scale",
    cat: "vc_framework",
    stage: ["Series A"],
    consensus: 4,
    insight: "Address the 'can this scale in Europe' question head-on.",
    fit: "UK/EU founders raising from European VCs.",
    olivia_action: "Add explicit European market expansion slide.",
  },
  {
    id: 16,
    name: "Accel",
    tag: "Prepared Mind",
    cat: "vc_framework",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Show you've thought about what could go wrong.",
    fit: "Mature founders who can discuss risks honestly.",
    olivia_action: "Add 'What keeps us up at night' slide.",
  },
  {
    id: 17,
    name: "Balderton",
    tag: "European Champion",
    cat: "vc_framework",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Position as the European leader in your category.",
    fit: "UK startups with European expansion ambitions.",
    olivia_action: "Add European market leadership positioning.",
  },
  {
    id: 18,
    name: "LocalGlobe",
    tag: "Seed Specialist",
    cat: "vc_framework",
    stage: ["Seed"],
    consensus: 4,
    insight: "Team and vision matter more than metrics at seed.",
    fit: "Very early-stage London founders.",
    olivia_action: "Lead with founder story and vision.",
  },
  {
    id: 19,
    name: "Notion Capital",
    tag: "B2B SaaS Focus",
    cat: "vc_framework",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "NDR, CAC payback, magic number — know your SaaS metrics.",
    fit: "B2B SaaS founders with established metrics.",
    olivia_action: "Add SaaS metrics deep-dive slide.",
  },
  {
    id: 20,
    name: "First Round",
    tag: "Community First",
    cat: "vc_framework",
    stage: ["Pre-seed", "Seed"],
    consensus: 4,
    insight: "Founders who help other founders win.",
    fit: "Founders with strong community involvement.",
    olivia_action: "Add community contribution slide.",
  },

  // ── AI / MODERN (21-35) ──
  {
    id: 21,
    name: "Synthesia",
    tag: "AI Cost-Collapse",
    cat: "ai_modern",
    stage: ["Seed", "Series A"],
    consensus: 5,
    insight: "Show the 10x cost reduction enabled by AI.",
    fit: "AI startups replacing expensive human labor.",
    olivia_action: "Add cost comparison: traditional vs AI-powered.",
    year: 2017,
  },
  {
    id: 22,
    name: "Writer",
    tag: "Enterprise AI Moat",
    cat: "ai_modern",
    stage: ["Series A"],
    consensus: 4,
    insight: "Enterprise AI needs SOC2, GDPR, custom models.",
    fit: "Enterprise AI founders targeting large customers.",
    olivia_action: "Add enterprise readiness checklist slide.",
  },
  {
    id: 23,
    name: "Gong",
    tag: "Revenue Intelligence",
    cat: "ai_modern",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Turn conversations into insights. AI augments, doesn't replace.",
    fit: "AI tools that enhance human decision-making.",
    olivia_action: "Show human + AI collaboration metrics.",
  },
  {
    id: 24,
    name: "Seek AI",
    tag: "Niche-Down AI",
    cat: "ai_modern",
    stage: ["Seed"],
    consensus: 4,
    insight: "Vertical AI beats horizontal. Own one domain deeply.",
    fit: "Vertical AI startups with domain expertise.",
    olivia_action: "Add vertical specialization moat slide.",
  },
  {
    id: 25,
    name: "Jasper",
    tag: "AI Content Engine",
    cat: "ai_template",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Templates + AI = scalable output.",
    fit: "AI content generation tools.",
    olivia_action: "Show template library + customization.",
  },
  {
    id: 26,
    name: "Copy.ai",
    tag: "AI Writing Assistant",
    cat: "ai_template",
    stage: ["Seed"],
    consensus: 3,
    insight: "First-mover in AI writing. Speed matters.",
    fit: "AI writing tools for marketing.",
    olivia_action: "Show output quality comparison.",
  },
  {
    id: 27,
    name: "Runway",
    tag: "Creative AI",
    cat: "ai_modern",
    stage: ["Series A"],
    consensus: 4,
    insight: "AI as a creative tool, not replacement.",
    fit: "AI tools for creative professionals.",
    olivia_action: "Add creator testimonials slide.",
    year: 2018,
  },
  {
    id: 28,
    name: "Midjourney",
    tag: "AI Art Revolution",
    cat: "ai_modern",
    stage: ["Seed"],
    consensus: 4,
    insight: "Community-driven AI. Discord as distribution.",
    fit: "AI tools with strong community engagement.",
    olivia_action: "Add community growth metrics.",
    year: 2022,
  },
  {
    id: 29,
    name: "Anthropic",
    tag: "AI Safety First",
    cat: "ai_modern",
    stage: ["Series A", "Series B"],
    consensus: 5,
    insight: "Safety as a moat. Responsible AI wins enterprise.",
    fit: "AI companies with strong safety positioning.",
    olivia_action: "Add AI safety and ethics slide.",
  },
  {
    id: 30,
    name: "Cohere",
    tag: "Enterprise LLM",
    cat: "ai_modern",
    stage: ["Series A"],
    consensus: 4,
    insight: "Custom models for enterprise. Not one-size-fits-all.",
    fit: "Enterprise AI infrastructure companies.",
    olivia_action: "Add enterprise customization capabilities.",
  },
  {
    id: 31,
    name: "Hugging Face",
    tag: "Open Source AI",
    cat: "ai_modern",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Open source builds trust. Commercial on top.",
    fit: "Open source AI companies with commercial layer.",
    olivia_action: "Add open source community metrics.",
  },
  {
    id: 32,
    name: "Stability AI",
    tag: "Democratized AI",
    cat: "ai_modern",
    stage: ["Seed", "Series A"],
    consensus: 3,
    insight: "Open models, community-driven development.",
    fit: "Open AI model companies.",
    olivia_action: "Add model accessibility slide.",
    year: 2020,
  },
  {
    id: 33,
    name: "Perplexity",
    tag: "AI Search",
    cat: "ai_modern",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Citations matter. AI with sources wins trust.",
    fit: "AI search and research tools.",
    olivia_action: "Add accuracy and citation methodology.",
    year: 2022,
  },
  {
    id: 34,
    name: "Notion AI",
    tag: "AI in Product",
    cat: "ai_template",
    stage: ["Series A"],
    consensus: 4,
    insight: "AI as a feature, not a product. Embed in workflow.",
    fit: "Products adding AI capabilities.",
    olivia_action: "Show AI integration into existing workflow.",
  },
  {
    id: 35,
    name: "Cursor",
    tag: "AI-Native IDE",
    cat: "ai_modern",
    stage: ["Seed"],
    consensus: 4,
    insight: "Built for AI from day one, not bolted on.",
    fit: "AI-native developer tools.",
    olivia_action: "Add AI-first architecture slide.",
    year: 2023,
  },

  // ── FINTECH (36-45) ──
  {
    id: 36,
    name: "Stripe",
    tag: "Developer-First Fintech",
    cat: "fintech",
    stage: ["Seed", "Series A"],
    consensus: 5,
    insight: "7 lines of code. Developer experience is the product.",
    fit: "Developer-focused fintech infrastructure.",
    olivia_action: "Add code snippet showing simplicity.",
    year: 2010,
  },
  {
    id: 37,
    name: "Revolut",
    tag: "Super App Banking",
    cat: "fintech",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Start with one killer feature, expand to super app.",
    fit: "Consumer fintech with expansion roadmap.",
    olivia_action: "Show feature expansion timeline.",
    year: 2015,
  },
  {
    id: 38,
    name: "Monzo",
    tag: "Community Banking",
    cat: "fintech",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Community-first banking. Users as advocates.",
    fit: "Community-driven fintech products.",
    olivia_action: "Add community engagement metrics.",
    year: 2015,
  },
  {
    id: 39,
    name: "Wise",
    tag: "Transparent Pricing",
    cat: "fintech",
    stage: ["Series A"],
    consensus: 5,
    insight: "Show the fee comparison. Transparency wins.",
    fit: "Fintech disrupting hidden fees.",
    olivia_action: "Add fee comparison table vs incumbents.",
    year: 2011,
  },
  {
    id: 40,
    name: "Plaid",
    tag: "Financial Infrastructure",
    cat: "fintech",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Be the picks and shovels, not the gold miner.",
    fit: "Fintech infrastructure plays.",
    olivia_action: "Show ecosystem of companies you enable.",
    year: 2013,
  },
  {
    id: 41,
    name: "Klarna",
    tag: "BNPL Revolution",
    cat: "fintech",
    stage: ["Series A"],
    consensus: 4,
    insight: "Merchants pay for higher conversion.",
    fit: "B2B2C fintech models.",
    olivia_action: "Show merchant ROI metrics.",
    year: 2005,
  },
  {
    id: 42,
    name: "Robinhood",
    tag: "Zero Commission",
    cat: "fintech",
    stage: ["Seed"],
    consensus: 3,
    insight: "Free as a feature. Monetize elsewhere.",
    fit: "Freemium fintech models.",
    olivia_action: "Show revenue model beyond the free product.",
    year: 2013,
  },
  {
    id: 43,
    name: "Checkout.com",
    tag: "Enterprise Payments",
    cat: "fintech",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Enterprise payments need reliability, not features.",
    fit: "Enterprise payment infrastructure.",
    olivia_action: "Add uptime and reliability metrics.",
    year: 2012,
  },
  {
    id: 44,
    name: "Coinbase",
    tag: "Education-First Crypto",
    cat: "fintech",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Education before transaction. Build trust first.",
    fit: "Crypto and DeFi companies.",
    olivia_action: "Add user education journey slide.",
    year: 2012,
  },
  {
    id: 45,
    name: "Starling",
    tag: "Profitable Challenger",
    cat: "fintech",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Path to profitability matters. Not just growth.",
    fit: "Challenger banks with unit economics.",
    olivia_action: "Add unit economics and path to profit.",
    year: 2014,
  },

  // ── LONDON / UK SPECIFIC (46-55) ──
  {
    id: 46,
    name: "Gradient Labs",
    tag: "London AI Specificity",
    cat: "london_uk",
    stage: ["Seed"],
    consensus: 4,
    insight: "London AI talent advantage. Name the universities.",
    fit: "London AI startups leveraging local talent.",
    olivia_action: "Add London AI ecosystem positioning.",
  },
  {
    id: 47,
    name: "London AI Doc Engine",
    tag: "Document Automation",
    cat: "london_uk",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Legal tech meets AI. UK regulatory advantage.",
    fit: "Legal and regulatory tech in UK market.",
    olivia_action: "Add UK regulatory compliance advantage.",
  },
  {
    id: 48,
    name: "Deliveroo",
    tag: "London-First Expansion",
    cat: "london_uk",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "London density perfect for delivery. Expand from strength.",
    fit: "Logistics and delivery startups.",
    olivia_action: "Add London market density metrics.",
    year: 2013,
  },
  {
    id: 49,
    name: "Farfetch",
    tag: "London Luxury Tech",
    cat: "london_uk",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "London as luxury gateway. Fashion meets tech.",
    fit: "Luxury and fashion tech companies.",
    olivia_action: "Add London luxury market positioning.",
    year: 2007,
  },
  {
    id: 50,
    name: "Improbable",
    tag: "Deep Tech London",
    cat: "london_uk",
    stage: ["Series A"],
    consensus: 3,
    insight: "Deep tech needs patient capital. Position for it.",
    fit: "Deep tech companies with long development cycles.",
    olivia_action: "Add technology development roadmap.",
    year: 2012,
  },
  {
    id: 51,
    name: "Darktrace",
    tag: "UK Cyber Security",
    cat: "london_uk",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "UK government contracts as validation.",
    fit: "Cybersecurity companies targeting UK market.",
    olivia_action: "Add UK government and enterprise customers.",
    year: 2013,
  },
  {
    id: 52,
    name: "Graphcore",
    tag: "UK AI Hardware",
    cat: "london_uk",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "UK chip design heritage. Build on history.",
    fit: "AI hardware companies with UK roots.",
    olivia_action: "Add UK hardware engineering heritage.",
    year: 2016,
  },
  {
    id: 53,
    name: "Cazoo",
    tag: "UK Used Cars",
    cat: "london_uk",
    stage: ["Series A"],
    consensus: 3,
    insight: "UK right-hand drive advantage. Natural moat.",
    fit: "Automotive tech in UK market.",
    olivia_action: "Add UK-specific market dynamics.",
    year: 2018,
  },
  {
    id: 54,
    name: "Babylon Health",
    tag: "NHS Partnership",
    cat: "london_uk",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "NHS integration as distribution. B2G2C model.",
    fit: "Healthcare tech with NHS pathway.",
    olivia_action: "Add NHS partnership strategy.",
    year: 2013,
  },
  {
    id: 55,
    name: "GoCardless",
    tag: "UK Payments Rails",
    cat: "london_uk",
    stage: ["Series A"],
    consensus: 4,
    insight: "Direct Debit reimagined. UK payment culture.",
    fit: "UK payment infrastructure companies.",
    olivia_action: "Add UK payment behavior insights.",
    year: 2011,
  },

  // ── SAAS / B2B (56-65) ──
  {
    id: 56,
    name: "Figma",
    tag: "Collaborative Design",
    cat: "saas",
    stage: ["Seed", "Series A"],
    consensus: 5,
    insight: "Browser-based collaboration kills desktop software.",
    fit: "Collaborative software replacing desktop apps.",
    olivia_action: "Add collaboration metrics and multiplayer usage.",
    year: 2012,
  },
  {
    id: 57,
    name: "Notion",
    tag: "All-in-One Workspace",
    cat: "saas",
    stage: ["Seed", "Series A"],
    consensus: 5,
    insight: "Replace 5 tools with 1. Consolidation play.",
    fit: "Workspace consolidation products.",
    olivia_action: "Show tools replaced and consolidation value.",
    year: 2016,
  },
  {
    id: 58,
    name: "Airtable",
    tag: "No-Code Database",
    cat: "saas",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Spreadsheet power, database structure, no code.",
    fit: "No-code and low-code tools.",
    olivia_action: "Add user-created use cases slide.",
    year: 2012,
  },
  {
    id: 59,
    name: "Linear",
    tag: "Developer Tools UX",
    cat: "saas",
    stage: ["Seed"],
    consensus: 4,
    insight: "Developers care about speed. 50ms matters.",
    fit: "Developer productivity tools.",
    olivia_action: "Add performance benchmarks.",
    year: 2019,
  },
  {
    id: 60,
    name: "Loom",
    tag: "Async Video",
    cat: "saas",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Video is more human than text. Async is more efficient.",
    fit: "Async communication tools.",
    olivia_action: "Add async communication efficiency metrics.",
    year: 2015,
  },
  {
    id: 61,
    name: "Calendly",
    tag: "Meeting Scheduling",
    cat: "saas",
    stage: ["Seed"],
    consensus: 4,
    insight: "Single-purpose tools that do one thing perfectly.",
    fit: "Single-purpose productivity tools.",
    olivia_action: "Add time saved per user metrics.",
    year: 2013,
  },
  {
    id: 62,
    name: "Miro",
    tag: "Visual Collaboration",
    cat: "saas",
    stage: ["Series A"],
    consensus: 4,
    insight: "Remote work needs visual collaboration. COVID accelerator.",
    fit: "Remote collaboration tools.",
    olivia_action: "Add remote work adoption trends.",
    year: 2011,
  },
  {
    id: 63,
    name: "Datadog",
    tag: "Observability Platform",
    cat: "saas",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Consolidate monitoring tools. One platform to rule them all.",
    fit: "DevOps and observability platforms.",
    olivia_action: "Add tool consolidation ROI.",
    year: 2010,
  },
  {
    id: 64,
    name: "MongoDB",
    tag: "Developer Database",
    cat: "saas",
    stage: ["Series A"],
    consensus: 4,
    insight: "Developers choose the database. Bottom-up adoption.",
    fit: "Developer-first infrastructure.",
    olivia_action: "Add developer community metrics.",
    year: 2007,
  },
  {
    id: 65,
    name: "GitLab",
    tag: "All-in-One DevOps",
    cat: "saas",
    stage: ["Series A", "Series B"],
    consensus: 4,
    insight: "Single application for entire DevOps lifecycle.",
    fit: "DevOps platform companies.",
    olivia_action: "Add DevOps workflow consolidation.",
    year: 2014,
  },

  // ── CONSUMER (66-75) ──
  {
    id: 66,
    name: "TikTok",
    tag: "Algorithm-First Content",
    cat: "consumer",
    stage: ["Series A"],
    consensus: 4,
    insight: "The algorithm is the product. Content finds you.",
    fit: "Consumer apps with strong recommendation engines.",
    olivia_action: "Add algorithm engagement metrics.",
    year: 2016,
  },
  {
    id: 67,
    name: "Discord",
    tag: "Community Platform",
    cat: "consumer",
    stage: ["Seed", "Series A"],
    consensus: 4,
    insight: "Communities, not networks. Depth over breadth.",
    fit: "Community-first consumer platforms.",
    olivia_action: "Add community engagement depth metrics.",
    year: 2015,
  },
  {
    id: 68,
    name: "Spotify",
    tag: "Freemium Music",
    cat: "consumer",
    stage: ["Series A"],
    consensus: 4,
    insight: "Free tier as marketing. Premium as product.",
    fit: "Freemium consumer products.",
    olivia_action: "Add free-to-paid conversion funnel.",
    year: 2006,
  },
  {
    id: 69,
    name: "Netflix",
    tag: "Content Investment",
    cat: "consumer",
    stage: ["Series B", "Growth"],
    consensus: 4,
    insight: "Invest in original content. Own the library.",
    fit: "Content-driven consumer platforms.",
    olivia_action: "Add content investment and ROI metrics.",
    year: 1997,
  },
  {
    id: 70,
    name: "Peloton",
    tag: "Hardware + Content",
    cat: "consumer",
    stage: ["Series A"],
    consensus: 3,
    insight: "Hardware creates lock-in. Content creates retention.",
    fit: "Hardware + subscription consumer products.",
    olivia_action: "Add hardware + content flywheel.",
    year: 2012,
  },
  {
    id: 71,
    name: "Duolingo",
    tag: "Gamified Learning",
    cat: "consumer",
    stage: ["Seed", "Series A"],
    consensus: 5,
    insight: "Gamification drives daily engagement. Streaks matter.",
    fit: "Consumer edtech with gamification.",
    olivia_action: "Add gamification and retention metrics.",
    year: 2011,
  },
  {
    id: 72,
    name: "Calm",
    tag: "Wellness Subscription",
    cat: "consumer",
    stage: ["Series A"],
    consensus: 4,
    insight: "Mental health is mainstream. No longer niche.",
    fit: "Mental health and wellness apps.",
    olivia_action: "Add mental health market trends.",
    year: 2012,
  },
  {
    id: 73,
    name: "Headspace",
    tag: "Meditation Mainstream",
    cat: "consumer",
    stage: ["Series A"],
    consensus: 4,
    insight: "Celebrity voices add credibility. Partnerships matter.",
    fit: "Wellness apps with celebrity/brand partnerships.",
    olivia_action: "Add partnership strategy slide.",
    year: 2010,
  },
  {
    id: 74,
    name: "Strava",
    tag: "Social Fitness",
    cat: "consumer",
    stage: ["Series A"],
    consensus: 4,
    insight: "Social features drive engagement beyond utility.",
    fit: "Social fitness and activity tracking.",
    olivia_action: "Add social engagement metrics.",
    year: 2009,
  },
  {
    id: 75,
    name: "Snapchat",
    tag: "Contrarian Thesis",
    cat: "consumer",
    stage: ["Series A"],
    consensus: 3,
    insight: "Bet against permanence. Ephemeral is the future.",
    fit: "London founders with counter-consensus thesis.",
    olivia_action: "Add contrarian framing slide.",
    year: 2012,
    slideCount: 14,
  },
];

// ─────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────

export function getDeck(id: number): PitchDeckArchetype | undefined {
  return DECKS.find((d) => d.id === id);
}

export function getDeckByName(name: string): PitchDeckArchetype | undefined {
  return DECKS.find((d) => d.name.toLowerCase() === name.toLowerCase());
}

export function getDecksByCategory(cat: DeckCategory): PitchDeckArchetype[] {
  return DECKS.filter((d) => d.cat === cat);
}

export function getDecksByStage(stage: string): PitchDeckArchetype[] {
  return DECKS.filter((d) =>
    d.stage.some((s) => s.toLowerCase() === stage.toLowerCase()) ||
    d.stage.includes("Any")
  );
}

export function getArchetypeCount(): number {
  return DECKS.length;
}
