export const dynamic = "force-dynamic";

import { Suspense } from "react";
import Link from "next/link";
import { auth } from "@clerk/nextjs/server";
import { getDocuments, getDocumentFilterOptions } from "@/lib/queries/documents";
import { getPackages } from "@/lib/queries/packages";
import { DocumentCard } from "@/components/documents/DocumentCard";
import { DocumentFilters } from "@/components/documents/DocumentFilters";
import { PackageCard } from "@/components/packages/PackageCard";
import { CORE_COLLECTION_SLUGS, TEMPLATE_COUNT, COLLECTION_COUNT } from "@/lib/document-registry";

export const metadata = {
  title: "Document Library — London Tech Map",
  description: "Strategic document library — browse, filter, and add documents to outreach packages.",
};

type DocTab = "templates" | "packages" | "ecosystem";

interface DocumentsPageProps {
  searchParams: {
    tab?: string;
    collection?: string;
    audience?: string;
    purpose?: string;
    confidentiality?: string;
    search?: string;
  };
}

/** Collection slugs generated by the cascade pipeline — NOT packageable */
const CASCADE_COLLECTION_PREFIXES = ["cascade-"];

function isCascadeDoc(collectionSlug: string): boolean {
  return CASCADE_COLLECTION_PREFIXES.some((prefix) => collectionSlug.startsWith(prefix));
}

function isCoreTemplate(collectionSlug: string): boolean {
  return CORE_COLLECTION_SLUGS.has(collectionSlug);
}

export default async function DocumentsPage({ searchParams }: DocumentsPageProps) {
  const { userId } = auth();

  // Load user's Packages alongside the public documents/template list
  // so the "Packages" tab can surface the user's real outreach
  // bundles. Anonymous visitors get an empty list — the tab still
  // renders a sign-in CTA in that case.
  const [documents, filterOptions, userPackages] = await Promise.all([
    getDocuments({
      collectionId: searchParams.collection,
      audienceType: searchParams.audience,
      purposeType: searchParams.purpose,
      confidentiality: searchParams.confidentiality,
      search: searchParams.search,
    }),
    getDocumentFilterOptions(),
    userId ? getPackages({ ownerUserId: userId }) : Promise.resolve([]),
  ]);

  // Split collections for the two independent dropdowns
  const businessCollections = filterOptions.collections.filter(
    (c) => !c.slug.startsWith("cascade-")
  );
  const generalCollections = filterOptions.collections.filter(
    (c) => c.slug.startsWith("cascade-")
  );

  // Split documents into the two buckets each tab needs:
  //   - coreTemplateDocs → "templates" tab (12-collection core library).
  //   - generalDocs      → "ecosystem" tab (cascade-* research).
  // The "packages" tab is now driven by `userPackages` (real Package
  // rows loaded above), not by Documents.
  const coreTemplateDocs = documents.filter((doc) => isCoreTemplate(doc.collection.slug));
  const generalDocs = documents
    .filter((doc) => isCascadeDoc(doc.collection.slug))
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  // Group core templates by collection for organized display
  const coreDocsByCollection = new Map<string, { name: string; docs: typeof coreTemplateDocs }>();
  for (const doc of coreTemplateDocs) {
    const key = doc.collection.slug;
    if (!coreDocsByCollection.has(key)) {
      coreDocsByCollection.set(key, { name: doc.collection.name, docs: [] });
    }
    coreDocsByCollection.get(key)!.docs.push(doc);
  }
  const sortedCoreGroups = Array.from(coreDocsByCollection.entries()).sort(
    ([, a], [, b]) => a.name.localeCompare(b.name),
  );

  // userDocsByCollection / sortedUserGroups were removed alongside
  // the legacy "Your Packages = Your Documents" misnomer. Real
  // Packages are loaded via getPackages() above and rendered in the
  // Packages tab via PackageCard.

  // Resolve active tab — default to "templates"
  const validTabs: DocTab[] = ["templates", "packages", "ecosystem"];
  const activeTab: DocTab = validTabs.includes(searchParams.tab as DocTab) ? (searchParams.tab as DocTab) : "templates";

  // Compute per-tab record count for the filter bar. The "packages"
  // tab now reflects the count of real Packages (not the legacy
  // user-doc grouping that previously lived under that label).
  const activeTabCount =
    activeTab === "templates" ? coreTemplateDocs.length :
    activeTab === "ecosystem" ? generalDocs.length :
    activeTab === "packages" ? userPackages.length :
    documents.length;

  return (
    <div className="mx-auto max-w-7xl overflow-x-hidden px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-6 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-[var(--foreground)]">Document Library</h1>
          <p className="mt-1 text-sm text-[var(--muted)]">
            Browse strategic documents — filter by collection, audience, purpose, or confidentiality level.
          </p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <Link
            href="/documents/saved"
            className="flex items-center gap-2 rounded-md border border-[var(--card-border)] px-3 py-2 text-xs text-[var(--muted)] hover:text-amber-300 hover:border-amber-500/30 transition-colors"
          >
            <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
            </svg>
            Saved
          </Link>
          <Link
            href="/documents/new"
            className="flex items-center gap-2 rounded-md bg-indigo-600 px-3 py-2 text-xs font-medium text-white hover:bg-indigo-500 transition-colors"
          >
            <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 5v14" />
              <path d="M5 12h14" />
            </svg>
            New
          </Link>
        </div>
      </div>

      {/* ═══ FILTERS — Row 1 (3 dropdown-buttons) + Row 2 (sub-filters) ═══ */}
      <Suspense fallback={null}>
        <DocumentFilters
          businessCollections={businessCollections}
          generalCollections={generalCollections}
          resultCount={activeTabCount}
        />
      </Suspense>

      {/* ═══ CORE TEMPLATES SECTION ═══ */}
      {activeTab === "templates" && (
        <div className="mt-8">
          {/* Section header */}
          <div
            className="relative rounded-xl px-6 py-5 mb-6 overflow-hidden"
            style={{
              background: "linear-gradient(135deg, rgba(15, 23, 42, 0.92) 0%, rgba(10, 14, 26, 0.95) 100%)",
              border: "1px solid rgba(196, 169, 106, 0.15)",
              boxShadow: "0 2px 12px rgba(0, 0, 0, 0.3), 0 0 20px rgba(196, 169, 106, 0.03)",
            }}
          >
            {/* Top accent line */}
            <div
              className="absolute inset-x-0 top-0 h-[1px]"
              style={{ background: "linear-gradient(90deg, transparent 5%, rgba(196,169,106,0.3) 30%, rgba(196,169,106,0.45) 50%, rgba(196,169,106,0.3) 70%, transparent 95%)" }}
            />
            <div className="flex items-start gap-3">
              <div
                className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                style={{
                  background: "linear-gradient(135deg, rgba(196, 169, 106, 0.15) 0%, rgba(196, 169, 106, 0.06) 100%)",
                  border: "1px solid rgba(196, 169, 106, 0.25)",
                }}
              >
                <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="rgba(196,169,106,1)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                  <path d="M5 2H4a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6H5Z" />
                  <path d="M12 18v-6" />
                  <path d="M9 15h6" />
                </svg>
              </div>
              <div>
                <h2 className="text-base font-semibold" style={{ color: "rgba(196, 169, 106, 1)" }}>
                  Core Templates
                </h2>
                <p className="mt-1 text-xs leading-relaxed" style={{ color: "#b0bec5" }}>
                  {TEMPLATE_COUNT} turn-key company document templates for investors, partners, acquirers, and fund managers. Fill in each template with your company data — Olivia can help you complete them from conversation. Once filled, assemble them into professional outreach packages.
                </p>
                <p className="mt-1.5 text-[11px] font-medium tabular-nums" style={{ color: "rgba(196, 169, 106, 0.7)" }}>
                  {coreTemplateDocs.length} templates across {sortedCoreGroups.length} collections
                </p>
              </div>
            </div>
          </div>

          {/* Show documents only when a collection is selected from the dropdown */}
          {searchParams.collection ? (
            <>
              {sortedCoreGroups.map(([slug, { name, docs }]) => (
                <div key={slug} className="mb-8">
                  <div className="flex items-center gap-3 mb-3">
                    <h3 className="text-sm font-semibold text-[var(--foreground)]">{name}</h3>
                    <span className="text-[11px] text-[var(--muted)] tabular-nums">{docs.length}</span>
                    <div className="flex-1 h-[1px] bg-[var(--card-border)]" />
                  </div>
                  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                    {docs.map((doc) => (
                      <DocumentCard
                        key={doc.id}
                        id={doc.id}
                        title={doc.title}
                        slug={doc.slug}
                        documentType={doc.documentType}
                        audienceType={doc.audienceType}
                        purposeType={doc.purposeType}
                        formatType={doc.formatType}
                        confidentiality={doc.confidentiality}
                        isTemplate={doc.isTemplate}
                        ownerUserId={doc.ownerUserId}
                        summary={doc.summary}
                        collectionName={doc.collection.name}
                        moduleCount={doc._count.modules}
                        versionCount={doc._count.versions}
                        packageCount={doc._count.packageDocs}
                        contentSourceType={doc.contentSourceType}
                        createdAt={doc.createdAt.toISOString()}
                      />
                    ))}
                  </div>
                </div>
              ))}
            </>
          ) : (
            <div className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] p-8 text-center">
              <svg className="mx-auto h-8 w-8 mb-3" viewBox="0 0 24 24" fill="none" stroke="rgba(196,169,106,0.5)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="m6 9 6 6 6-6" />
              </svg>
              <p className="text-sm text-[var(--muted)]">
                Select a collection from the <span style={{ color: "rgba(196, 169, 106, 0.9)" }}>Business Documents</span> dropdown above to browse templates.
              </p>
              <p className="mt-1 text-xs text-[var(--foreground)]/40">
                {coreTemplateDocs.length} templates across {sortedCoreGroups.length} collections available.
              </p>
            </div>
          )}
        </div>
      )}

      {/* ═══ YOUR PACKAGES SECTION ═══ */}
      {activeTab === "packages" && (
        <div>
          <div
            className="relative rounded-xl px-6 py-5 mb-6 overflow-hidden"
            style={{
              background: "linear-gradient(135deg, rgba(15, 23, 42, 0.92) 0%, rgba(10, 14, 26, 0.95) 100%)",
              border: "1px solid rgba(52, 211, 153, 0.15)",
              boxShadow: "0 2px 12px rgba(0, 0, 0, 0.3), 0 0 20px rgba(52, 211, 153, 0.03)",
            }}
          >
            <div
              className="absolute inset-x-0 top-0 h-[1px]"
              style={{ background: "linear-gradient(90deg, transparent 5%, rgba(52,211,153,0.3) 30%, rgba(52,211,153,0.45) 50%, rgba(52,211,153,0.3) 70%, transparent 95%)" }}
            />
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-start gap-3">
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                  style={{
                    background: "linear-gradient(135deg, rgba(52, 211, 153, 0.15) 0%, rgba(52, 211, 153, 0.06) 100%)",
                    border: "1px solid rgba(52, 211, 153, 0.25)",
                  }}
                >
                  <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="rgba(52,211,153,1)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <path d="M16 16h6" />
                    <path d="M19 13v6" />
                    <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                    <path d="M5 2H4a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6H5Z" />
                  </svg>
                </div>
                <div>
                  <h2 className="text-base font-semibold" style={{ color: "rgba(52, 211, 153, 1)" }}>
                    Your Packages
                  </h2>
                  <p className="mt-1 text-xs leading-relaxed" style={{ color: "#b0bec5" }}>
                    Curated bundles of your private documents, ready to share with investors, partners, or acquirers via tracked links.
                  </p>
                  <p className="mt-1.5 text-[11px] font-medium tabular-nums" style={{ color: "rgba(52, 211, 153, 0.7)" }}>
                    {userPackages.length} {userPackages.length === 1 ? "package" : "packages"}
                  </p>
                </div>
              </div>
              {userId && (
                <Link
                  href="/packages/new"
                  className="shrink-0 inline-flex items-center gap-1.5 rounded-md border border-emerald-500/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-medium text-emerald-300 hover:bg-emerald-500/15 transition-colors"
                >
                  <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <path d="M12 5v14" />
                    <path d="M5 12h14" />
                  </svg>
                  New Package
                </Link>
              )}
            </div>
          </div>

          {!userId ? (
            <div className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] p-12 text-center">
              <p className="text-sm text-[var(--muted)] mb-4">
                Sign in to view your outreach packages.
              </p>
              <Link
                href="/sign-in"
                className="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-4 py-2 text-xs font-medium text-white hover:bg-indigo-500 transition-colors"
              >
                Sign In
              </Link>
            </div>
          ) : userPackages.length === 0 ? (
            <div className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] p-12 text-center">
              <p className="text-sm text-[var(--muted)] mb-4">
                No packages yet. Add documents to a package from the dashboard My Documents tile, or build one from scratch.
              </p>
              <Link
                href="/packages/new"
                className="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-4 py-2 text-xs font-medium text-white hover:bg-indigo-500 transition-colors"
              >
                Create First Package
              </Link>
            </div>
          ) : (
            <div className="flex flex-wrap gap-5">
              {userPackages.map((pkg) => (
                <PackageCard key={pkg.id} pkg={pkg} layout="wrap" />
              ))}
            </div>
          )}
        </div>
      )}

      {/* ═══ ECOSYSTEM DOCUMENTS SECTION ═══ */}
      {activeTab === "ecosystem" && generalDocs.length > 0 && (
        <div>
          <div className="flex items-start gap-3 mb-6">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
              style={{
                background: "linear-gradient(135deg, rgba(99, 102, 241, 0.12) 0%, rgba(99, 102, 241, 0.04) 100%)",
                border: "1px solid rgba(99, 102, 241, 0.2)",
              }}
            >
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="rgba(129, 140, 248, 0.8)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
              </svg>
            </div>
            <div>
              <h2 className="text-base font-semibold text-[var(--foreground)]">Ecosystem Documents</h2>
              <p className="mt-0.5 text-xs text-[var(--muted)]">
                Research, insights, and reports sourced from across the London tech ecosystem.
              </p>
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {generalDocs.map((doc) => (
              <DocumentCard
                key={doc.id}
                id={doc.id}
                title={doc.title}
                documentType={doc.documentType}
                audienceType={doc.audienceType}
                purposeType={doc.purposeType}
                formatType={doc.formatType}
                confidentiality={doc.confidentiality}
                isTemplate={doc.isTemplate}
                ownerUserId={doc.ownerUserId}
                summary={doc.summary}
                collectionName={doc.collection.name}
                moduleCount={doc._count.modules}
                versionCount={doc._count.versions}
                packageCount={doc._count.packageDocs}
                contentSourceType={doc.contentSourceType}
                createdAt={doc.createdAt.toISOString()}
                variant="ecosystem"
              />
            ))}
          </div>
        </div>
      )}

      {/* ═══ EMPTY STATE ═══
          Packages tab now handles its own empty state inline (sign-in
          CTA vs "no packages yet" CTA), so it's intentionally absent
          from this fallback block. */}
      {((activeTab === "templates" && searchParams.collection && coreTemplateDocs.length === 0) ||
        (activeTab === "ecosystem" && generalDocs.length === 0)) && (
        <div className="mt-6 rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] p-12 text-center">
          <p className="text-sm text-[var(--muted)]">
            {activeTab === "templates" && "No documents found in this collection with the current filters."}
            {activeTab === "ecosystem" && "No ecosystem documents found. These are auto-generated from the data pipeline."}
          </p>
        </div>
      )}
    </div>
  );
}
